### ISSUE TITLE
Content to CIA - Handling two different SD cards

### ISSUE THREAD

**Issue by exegg** [d0k3/Decrypt9WIP#101]
Little background.

I have a console which at first, it had a 2 GB SD card. A few games were installed on it. SD#1

Then I bought another, bigger SD. SD#2. I forgot to copy SD#1 contents into SD#2 and proceeded to install other stuff. As you know, "Nintendo 3DS" folders can't be merged normally even if they belong to the same console. In order to play the older games on SD#1, I just switch them.

Now with the brand new feature of Content to CIA, I tried to extract my older games on SD#1 to install them on SD#2 but I get a "Game directory no found!" error. Only SD#2 gets recognized with this option.

The folder names in each SD are like this
/Nintendo 3DS/SAME NUMBER ID/DIFFERENT NUMBER ID

I tried renaming the second folder in the SD#1 but it didn't work. So, I assume this is normal for regular Nintendo security standards, but is it manageable? I'm obviously going through all this hassle since I deleted the original backups and due to my limited Internet connection I can't redownload them.

Thanks.

**Comment by d0k3** [comment]
Oh well... I could just tell you to consult the readme, but I'll give you a hint. Create a /files9/ directory on both SDs. Then tell me if it is solved.

**Comment by exegg** [comment]
Oh well, how dumb can I be? Problem solved.

And I did rename it back, only changed it to boot Decrypt9 with A9LH and then switched it off. Nothing happened. Thanks.
