### ISSUE TITLE
(Suggestion) Convert titles back into Decrypted 3ds format

### ISSUE THREAD

**Issue by Zetchzie** [d0k3/Decrypt9WIP#105]
so with the new cia feature would it be possible to convert stuff into decrypted 3ds files for Citra?

**Comment by ihaveamac** [comment]
not needed, you can extract a decrypted CIA and add ".cxi" to the end of the first content.

**Comment by Zetchzie** [comment]
plz explain this process if you will

**Comment by ihaveamac** [comment]
```
ctrtool --contents=contents game.cia
```
... then add ".cxi" to the file that starts with "contents.0000"

**Comment by Zetchzie** [comment]
cant get ctr to start

**Comment by ihaveamac** [comment]
why doesn't it start? how did you try to start it?

**Comment by Zetchzie** [comment]
ok it starts if i launch it in cmd but im still confused. say i have a cia file still encrypted or a title on 3ds im going to convert back into a cia how do go about decrypting it and using crt tool to make cxi?

**Comment by d0k3** [comment]
Convert SD to CIA -> Decrypt CIA (deep) -> use makerom or CTRtool on PC to do the remainder of the conversion.

As an additional hint,  CIAs created via the SD to CIA converter will be encrypted (if the original source was encrypted). Thus, you will want to deep decrypt the CIA first. Also, the conversion from CIA -> NCCH/NCSD will not be in D9, as that one is not exactly trivial and requires to re-generate certain data from scratch.

Closing this now.

**Comment by MelonGx** [comment]
1. Use SD Decrypter to dump decrypted .TMD and .APP
2. Copy .TMD and .APP to PC
3. Use SDto3DS to convert them into .3DS
4. Use NCCH/NCSD Decrypter to decrypt .3DS
Done.

**Comment by d0k3** [comment]
... Or just use the new SD CXI dumper ;)

**Comment by Zetchzie** [comment]
@d0k3 yea that feature is a godsend lol thanks for it
