### ISSUE TITLE
Content to CIA creates bad CIA file when creating SEED-encrypted titles

### ISSUE THREAD

**Issue by MelonGx** [d0k3/Decrypt9WIP#107]
Devmenu/FBI reported it that "This CIA is invalid".
Converting No-SEED titles is fine.

(Edited at 2016-11-02)
Rebuilt the CIA with 2016-10-21 release.
It can be installed properly.
So the "This CIA is invalid" case seems to be simply a file error.

But after the installation, there is one more SEED related problem occurs.
See the following comments for details.

**Comment by MelonGx** [comment]
I know that we still have the old method to convert a SEED title into proper CIA.
But if Content to CIA can be fixed for this, it will be much easier.

**Comment by d0k3** [comment]
I'll look into it, but there is something you can try. Open the CIA in a hex editor (GM9 f.e.) and zero out the four byte at 0x14. Then try installing it again

**Comment by d0k3** [comment]
Okay, I tried it myself. This has nothing to do with seed crypto cause other seed titles work. Can you give me the title this happened with? Was it the Sun & Moon demo? 

Also, please test the stuff I described above.

**Comment by d0k3** [comment]
And here's a test build you can try:
https://transfer.sh/KamnL/decrypt9wip-20161101-141552.zip
This one should work 100%. Once you're ready, let me know how that works for you.

**Comment by MelonGx** [comment]
Thanks. I'm now dumping that title again with the test build.
The title was 00040000001af500.
The error happened on installing the CIA on another 3DS which hadn't installed that title before.

**Comment by MelonGx** [comment]
The CIA built from the test build is installable now.
I'll try to build the CIA with 2016-10-17 and test it again later.

**Comment by d0k3** [comment]
Alright, thanks! The SD -> CIA converter tries to build CIAs that are as original as possible. For installed legit CIAs f.e., you will again get a legit CIA back after rebuilding. This also means that any crypto the installable content has (SEED / regular / 7x / Secure3 / Secure4) is kept (actually must be kept to keep the sigs intact).

You can fix this by running CIA decryptor (deep) after the conversion. Question now is, shouldn't that be handled by the SD -> CIA Converter itself, right? Tbh, I am unsure about that.

**Comment by MelonGx** [comment]
OK I'll try the SD to CIA -> CIA Decryptor (deep) to see whether it works or not.
BTW SD to CIA -> CIA Decryptor (shallow) results a "This CIA is invalid" and I don't know why, since this time it's not a file copy error.

**Comment by d0k3** [comment]
That could actually only happen if the SEED in your seeddb.bin is invalid. In that case, though, the SD to CIA decryptor would throw an error, too. Did it?

**Comment by MelonGx** [comment]
Tried that SD to CIA -> CIA Decryptor (deep) works without any "CIA invalid" issue.
It's OK now.

**Comment by MelonGx** [comment]
The shallow one was succeeded.
The SEED was already imported into seeddb.bin.
So I don't know why shallow didn't work.

**Comment by d0k3** [comment]
Just to clarify this... Are you trying to install this CIA on GW? If so, known GW issue (incomplete / improper sig patching). Otherwise I'd need to find out what's wrong with deep decryption.

**Comment by MelonGx** [comment]
Deep decryption is fine.
Shallow isn't.
It happened on Luma 6.3.1.

**Comment by MelonGx** [comment]
Since
1) SD to CIA
2) CIA Decryptor (Deep)
works,
no matter whether CIA Decryptor (Shallow) works or not, this issue is resolved.
