### ISSUE TITLE
NCCH Padgen not generating files

### ISSUE THREAD

**Issue by plasticblues** [d0k3/Decrypt9WIP#109]
Generating NCCH Padgen is not generating xorpad files, I have the ncchinfo file in the proper working directory, it appears that it is running and gives a success message however when I unmount the sd card and put it in to my PC I have no xorpad files on the SD card but I do have a new file called "s" which is about 1gb in size.

Using A9LH to boot Decrypt9WIP using a the up arrow, not sure if that has anything to do with it.

**Comment by d0k3** [comment]
Please upload the ncchinfo.bin file you used (don't worry, there is no copyrighted or identifying info in there). Also give me the log, or at least the relevant parts of it.

**Comment by d0k3** [comment]
Additional request: Tell me what you did use to create the ncchinfo.bin file

**Comment by plasticblues** [comment]
To the second request I'm using 3DS Conv to gen the ncchinfo.bin file.

Working on my other ticket then I'll gen the ncchinfos for you and give you a link.

**Comment by plasticblues** [comment]
This seems to be an issue with 3DSconv as when I generated the files using your script for ncchinfo it does work, so much for using newer guides to generate certain things. Again thank you for the help and sorry for the trouble.

**Comment by d0k3** [comment]
Actually, D9 should work ncchinfo.bins created with any tool. Can you still give me the bad ncchinfo.bin file? I want to take a look! :)

**Comment by plasticblues** [comment]
I'll have to redump the cart tonight while I'm at work, now that I can get dumps to cia working on rednand I kinda deleted the dumped 3ds files as I no longer needed them as well as the ncchinfo.bin. I'll host it ip tonight after work.

**Comment by ihaveamac** [comment]
I'd like to look at the "bad" ncchinfo.bin by 3dsconv too. it'd help me fix whatever issue there is.

**Comment by plasticblues** [comment]
I tried to reproduce this issue last night, but both times with more than one games nnchinfo.bin the xorpads generated properly. While this is weird when I was trying to figure out what was wrong I did find one other case of this happening:
https://gbatemp.net/threads/xorpads-never-save-to-sd-card.396338/

Post 3 mentions the "s" file problem which was what I was getting I assume, the xorpads would look as if they were generating but only 1 file with a single letter would be generated. I wish I could give a ncchinfo.bin that caused me issues, but I cannot reproduce it any more :\, I apologize.

**Comment by d0k3** [comment]
Yeah, but see the that on that discussion? The issue you described was in fact a known issue in D9 when using ncchinfo.bins generated with other tools, but that was fixed ages ago. Is there any chance you used a old release of D9 to generate the XORpads?
