### ISSUE TITLE
Decrypt9WIP dumping cart to cia, corrupt CIA files

### ISSUE THREAD

**Issue by plasticblues** [d0k3/Decrypt9WIP#110]
When dumping a cart to CIA I am getting a corrupt CIA file which cannot be installed by either FBI or BBM, I've tried dumping multiple times with multiple games but with no positive results.

The games I've tried dumping that are having this issue are:
Fire Emblem Awakening
Majora's Mask

**Comment by plasticblues** [comment]
The games I've tried dumping that are having this issue are:
Fire Emblem Awakening
Majora's Mask

**Comment by d0k3** [comment]
Can you give me the log? It's in a file called "Decrypt9.log". Also, does this happen with all carts for you?

**Comment by d0k3** [comment]
And, one more thing - you know this CIAs are only installable with patched sigs? What CFW are you using? Got any second 3DS you can try the same CIAs on?

**Comment by plasticblues** [comment]
For your second question, I'm using gateway emunand on top of luma a9lh.

**Comment by plasticblues** [comment]
Here are the status and logs of 3 titles:

The Legend Of Zelda Ocarina Of Time (CTR-P-AQEE-dec.cia) **Working** (Install Successful FBI):
`Selected: [Dump Cart to CIA]
Cartridge ID: 9000FEC2
Cartridge Type: CTR
Product ID: CTR-P-AQEE
Cartridge data size: 512MB
Cartridge used size: 459MB
Cartridge CIA size : 454MB

Decrypting partition #0 (454MB)...
Decryption success!!
Finalizing CIA file...

Verification success!
Dump Cart to CIA: succeeded!

Press B to return, START to reboot.

Unmounting SD card...`

The Legend Of Zelda Majoras Mask **Not Working** (Install Failed FBI and BBM):
`Selected: [Dump Cart to CIA]
Cartridge ID: 9002FAC2
Cartridge Type: CTR
Product ID: CTR-P-AJRE
Cartridge data size: 1024MB
Cartridge used size: 657MB
Cartridge CIA size : 630MB

Decrypting partition #0 (629MB)...
Decrypting partition #1 (1MB)...
Decryption success!!
Finalizing CIA file...

Verification success!
Dump Cart to CIA: succeeded!

Press B to return, START to reboot.

Unmounting SD card...`

FBI Error:
`Failed to install CIA file.
Result code: 0xD8E08025
Level: Permanent (27)
Summary: Invalid argument (7)
Module: AM (32)
Desc: Invalid NCCH (37)`

Fire Emblem Awakening **Not Working** (Install Failed FBI and BBM):
`Selected: [Dump Cart to CIA]
Cartridge ID: 9002F8C2
Cartridge Type: CTR
Product ID: CTR-P-AFEE
Cartridge data size: 2048MB
Cartridge used size: 1101MB
Cartridge CIA size : 1071MB

Decrypting partition #0 (1070MB)...
Decrypting partition #1 (0MB)...
Decryption success!!
Finalizing CIA file...

Verification success!
Dump Cart to CIA: succeeded!

Press B to return, START to reboot.

Unmounting SD card...`

FBI Error:
``

**Comment by plasticblues** [comment]
Alright so I've switched away from gateway to rednand seeing as upon futher googling it looks like gateway may be at fault here for not picking up some files, testing Fire Emblem now to see.

Results:
Well dang it worked, will test the other dump after I'm done eating

**Comment by plasticblues** [comment]
Alright, everything is working fine, this seems to be an issue with gateway etc. Sorry for the bother.

**Comment by d0k3** [comment]
This is a GW issue, correct. Team GW is too lazy to properly fix signatures for anything but the first content, so it worked for all carts that have no DLP and no manual (OOT, f.e.). Fixing this would take one of their devs literally an afternoon, but who am I telling this.. -_-. Anyways, you can try your luck with their support.

**Comment by plasticblues** [comment]
Thank you for your support, I do appreciate it. It kinda sucks because for some reason this was working previously with a similar gateway install minus A9LH but I'm not sure if I stripped the manuals etc out of them before, it was so long ago.
