### ISSUE TITLE
(Suggestion) CIA Builder (Sys/EmuNAND) show title name

### ISSUE THREAD

**Issue by miniluigi008** [d0k3/Decrypt9WIP#113]
It would be much easier to be able to select files off of the SD by title instead of their parent folder.

TL;DR: I dumped a folder full of updates (and could only cancel one operation at a time.)

Thanks for your hard work!

**Comment by d0k3** [comment]
I will make cancellation global in this option (= cancel all at once).

Showing actual titles, however, is not possible. That would require access to system services, which we don't have on ARM9 (after homemenu is launched we don't have access to certain stuff required for building CIA, so that's that).

For further reading, a while ago I requested the CIA builder to be included in FBI, which seems not possible:
https://github.com/Steveice10/FBI/issues/206

**Comment by miniluigi008** [comment]
Is it possible to offer the option for the Luma payload version? I thought Luma chain-loads before the homemenu is launched, or am I mistaken?

Otherwise if I understand you correctly...
boot with AL9H: (ARM9) ~~(system services)~~
homemenu: ~~(ARM9)~~ (system services)
... If so, that's a bummer.

Anyway, thanks for making cancellation global.

**Comment by miniluigi008** [comment]
Is there any way I could infer what the files might be on the SD from the parent folder by searching it online, or are the folder names unique to each system (something like a UUID)?

**Comment by d0k3** [comment]
The title ID is unique per game, not per console. Find it either via FBI, via the database you found (this only has retail cart releases, though) or via Google.

**Comment by d0k3** [comment]
Okay, cancel is now global on the SD CIA Builder features, starting with https://github.com/d0k3/Decrypt9WIP/commit/4493fae92b8d279d44a5a745fd5816cfbee09809

Maybe you can give it a try and provide me with feedback?
https://transfer.sh/OfMia/decrypt9wip-20161117-140614.zip

**Comment by miniluigi008** [comment]
Sure thing, I'll let you know if it works.

**Comment by miniluigi008** [comment]
Yup, the global operation cancellation works great. 🎉 

Something you could do in the future is allow cancellation while it's searching for tickets, as well as display how many folders are in a parent directory (it would help to get an idea of how long an operation might take before it is initiated.)

I have no problems with the way those things are currently, but if you're bored you'll have some ideas to consider.

Thanks! 👍

**Comment by d0k3** [comment]
Alright, problem solved. I'll consider your two other suggestions later.
