### ISSUE TITLE
Cannot decrypt/encrypt a large number of title keys.

### ISSUE THREAD

**Issue by weirdal3333** [d0k3/Decrypt9WIP#114]
As stated, you can't encrypt or decrypt large numbers of title keys.

2000 keys definitely doesn't work.
"Too many/few entries specified: 2000"
is the error I get.

I suggest raising the limit to 10,000.

Also have a warning message saying: 'This could take more than 5 minutes. Please wait...'

**Comment by weirdal3333** [comment]
Also, maybe you could split the 'dectitlekeys.bin' into multiple files, and then process them one at a time.
Ex: 'dectitlekeys.bin_1','decttitlekeys.bin_2',etc.

Then there wouldn't be any problems with decrypting/encrypting titlekeys.

**Comment by d0k3** [comment]
Okay. Limit lifted in https://github.com/d0k3/Decrypt9WIP/commit/127cb7f6c4737a8a5573e19dab821d0bdb1232df
Also, there is now a progress indicator. 

Please test it and let me know if it works:
https://transfer.sh/LeIAH/decrypt9wip-20161121-182900.zip

**Comment by weirdal3333** [comment]
It works... Almost too well! On my Majora's mask n3DS, it encrypts and decrypts the '*titlekeys.bin' file almost instantly. It also was able to handle over 3000 titlekeys at once. I'd say that this is a successful bug fix.
