### ISSUE TITLE
Dumping titles installed on the NAND to decrypted CXI?

### ISSUE THREAD

**Issue by khang06** [d0k3/Decrypt9WIP#118]
It would be nice if I could dump and decrypt titles from NAND directly on the 3DS. The method I currently use is downloading from NUS, copying CIA to D9Game, decrypting, copying decrypted CIA to PC, and using ctrtool to turn it into a CXI.

**Comment by d0k3** [comment]
This will not be in D9, but it will be coming (and is actually already in the works) to GodMode9.
