### ISSUE TITLE
[Request] Dump & Decrypt all system file to .cia ?

### ISSUE THREAD

**Issue by Monotek18** [d0k3/Decrypt9WIP#120]
I'd like to know if it would be possible to dump all firmware file to a decrypted .cia
https://www.3dbrew.org/wiki/Title_list

Since I don't find a way to download them from the NUS because "yls8.mtheall.com/ninupdates" is down.

**Comment by d0k3** [comment]
This is coming, but for GodMode9, not D9. D9 simply does not have the capabilities to do this.
