### ISSUE TITLE
Decrypt9WIP shows incorrect free space on SD

### ISSUE THREAD

**Issue by khang06** [d0k3/Decrypt9WIP#122]
Decrypt9WIP shows 878MB of free space, but CTRXplorer and my PC show 3 gb of free space.
http://i.imgur.com/5PYX2Fw.png
http://i.imgur.com/eQaBBX9.png
This also happens in EmuNAND9 and deleting files do not change the size reported by them.

**Comment by khang06** [comment]
Fixed by reformatting with 32k clusters. Maybe 64k clusters is buggy?

**Comment by james-d-elliott** [comment]
I'd guess what ever call is used to get the free space returns information in blocks and there may be no way to get the cluster size. If there is it's possibly just not used yet.

**Comment by d0k3** [comment]
Already closed, but it is actually more likely D9 is right, and CTRXplorer / Windows are wrong. 64k clusters are uncommon. You could only try out if you filled that SD card (on Windows) with a single 879MB+ file. Too late, though, cause you already reformatted.
