### ISSUE TITLE
Compact MultiNAND/rednand setups dont seem to work. 

### ISSUE THREAD

**Issue by theholyduck** [d0k3/Decrypt9WIP#123]
Multinands created using the latest version of the [multi-emunandcreator](https://gbatemp.net/threads/release-3ds-multi-emunand-creator.381603/) seem to be incompatible with decrypt9s multinand support. if you create 4 emunand/rednands using this tool then they will pack inside 5gb and as i understand it use a magic byte or something to help software locate the positions of the nand dumps. 

This works great with luma3ds. but it does not work with decrypt9 which only recognizes the first red/emunand. and shows a second as a emunand option but with no emunands installed. 
IF i manually make a 8gb+ deadzone before the first partition then decrypt9 will show 4 emunand slots but i also have to use decrypt9 to read and write nand dumps for it. 

Is it possible to add support like luma3ds has for the more compact format multi-emunand creator uses?

**Comment by d0k3** [comment]
There is some stuff you can help me with. First of all, you've got a four RedNAND setup now, right? Can you extract the first sector (512 byte) of that SD card and upload it somewhere?

Instructions here:
https://mh-nexus.de/en/hxd/StarManSaveSectors.htm
... and, no worries, there is no private or copyrighted information in there.

Also, second thing I want to ask. Don't know how long it will take for me to add that support, but I may do it for GodMode9, too (unsure yet). MultiNand setups are not too common, compact ones are very rare. So... would you be willing to help test GodMode9, too, at a later point?

**Comment by theholyduck** [comment]
[firstsector.zip](https://github.com/d0k3/Decrypt9WIP/files/634718/firstsector.zip)
heres my first sector on my sdcard with the compact setup

i imagine https://github.com/AuroraWright/Luma3DS/blob/master/source/emunand.c and/or 
https://github.com/DarkMatterCore/Luma3DS/commit/5b6318ee3a2f17c2c5ac3815ffdbf421eb666785 will be able to help you with how the default, compact and legacy setups work. 

I was able to make a multinand compatible with decrypt9 by making enough room before the first formated partition on a seperate sdcard and using decrypt9 to write the 4 nands.. but i think this is the so called "legacy" spacing for nands.

**Comment by d0k3** [comment]
Solved in https://github.com/d0k3/Decrypt9WIP/commit/ea5360cd9b210289c5bb487a20a036a039fa1671

Thanks for testing, @theholyduck !
