### ISSUE TITLE
(Suggestion) Backup folder cache from SD

### ISSUE THREAD

**Issue by drfsupercenter** [d0k3/Decrypt9WIP#124]
I've been using D9WIP for quite some time on my a9lh system, and use the NAND backup/restore features on a regular basis.

But I just got into a situation where I accidentally wiped my tickets, and upon restoring the NAND it acted as if all 300 of my titles were newly installed - they were no longer in folders, and all gift-wrapped.

I understand there are a few files on the SD that store the icon arrangement, and you can backup and restore those to prevent that sort of issue.

But of course since I've been relying on D9WIP to backup and restore my NANDs I haven't even bothered to back that up.

Could it maybe be an option when creating the backups to also backup the icon cache? As far as I know, that's the only stuff stored on the SD and not on the NAND (aside from the games themselves, which can be redownloaded/reinstalled)... all the rest is NAND extdata

**Comment by d0k3** [comment]
I somewhat wonder, how could you still have kept all the installed titles (which are installed in /Nintendo 3DS/<id0>/<id1>/) and have lost only the icon placement (the file for which is also in /Nintendo 3DS/<id0>/<id1>/)?

I'm not entirely adverse to putting an option for backup of that file in there, but I somehow wonder how you could end up in that situation, as you see.

**Comment by d0k3** [comment]
Okay, implemented with https://github.com/d0k3/Decrypt9WIP/commit/ad3e33cf273d3e02f22911fc59b27486e9d98e37

User button up/down to select the alternave filename containing the serial.

**Comment by d0k3** [comment]
Wrong issue :). Reopened, but please give me some mode info! :)

**Comment by d0k3** [comment]
Okay, there has been no additional info on this for quite some time, so I'm considering this solved. Feel free to reopen if you want to add something more.
