### ISSUE TITLE
Decryption Fail on building decrypted 190A00 (Megami Meguri) CIA or Deep decrypt it

### ISSUE THREAD

**Issue by MelonGx** [d0k3/Decrypt9WIP#126]
D9WIP: 20161113
Platform: Retail O3DS, A9LH SysNAND 11.2.0-35J

Selected: [CIA Builder (SysNAND/decr.)]
0x34 KeyY: set up from NAND

<id0> is <snip>
Use arrow keys and <A> to choose a folder
/title/00040000/00190a00

Building CIA from ID 0004000000190A00
Fetching TMD...
Searching for proper ticket...
Found ticket, injecting...
Console unique info found, wiping...
Writing CIA stub (14656 byte)...
Injecting content id 00000002 (331520 kB)...
Decrypting content id 00000002 (SD)...
Decrypting content id 00000002 (NCCH)...
Code / Crypto: CTR-N-KWMJ / 7x Seed 
Loading seed from NAND: ok
Decrypt ExHdr/ExeFS/RomFS (2kB/4839kB/319MB)
Verify ExHdr/ExeFS/RomFS: OK/Fail/Fail
Failed decrypting content
0x generated / 1x failed
CIA Builder (SysNAND/decr.): failed!

Press B to return, START to reboot.

Selected: [CIA Decryptor (deep)]
Opening /files9 ...

Processing CIA "0004000000190A00.cia"
Not a CIA or corrupt file
Failed!

CIA Decryptor (deep): failed!

Press B to return, START to reboot.

**Comment by MelonGx** [comment]
OK this is completely the same issue as #119.
Awaiting for a new update since all test build links on that issue are invalid now.

**Comment by d0k3** [comment]
This looks to me like a bad seed in your NAND (99.9% sure). Can you compile from master and (maybe) provide a proper seeddb.bin?

**Comment by MelonGx** [comment]
It's impossible because this is a self-dump.

**Comment by d0k3** [comment]
Just compile from master and try again. A self dump? From a cart? Then it would not have seed crypto.

**Comment by MelonGx** [comment]
Self-dump from my own purchase, but not from installed CIA.

**Comment by MelonGx** [comment]
Git clone'd it. What am I need to install to be able to "make release"?

**Comment by MelonGx** [comment]
OK. You're right.
After re-checking the log of building SEEDDB.bin, I found that the problem was no 190A00 SEED stored inside the NAND.

**Comment by MelonGx** [comment]
OK. This game does require a SEED.
If installing the original CIA without achieving a SEED, it gives me a SVCBreak (Luma ErrDisp).

Then the problem is - why current Decrypt9WIP cannot find the proper SEED of this game?
BTW, my SEEDDB.bin already has 48 SEEDs.

**Comment by d0k3** [comment]
Retry building the decrypted CIA with the ,ost recent build of D9 you just downloaded. Then show me the output.

**Comment by d0k3** [comment]
So, this looks like the seed is not in your NAND. Can you actually play this title on your console?

**Comment by MelonGx** [comment]
I just said that, when I installed the encrypted game, not to get the SEED, it crashed and gave me a Luma ErrDisp SVCBreak screen .

**Comment by d0k3** [comment]
Yup, show me the seedsave.bin.

**Comment by d0k3** [comment]
Also, another thing to try. Grab the latest build of GodMode9 and try to decrypt the CIA file in that (use the A button on the file).

**Comment by MelonGx** [comment]
[seedsave_emu.zip](https://github.com/d0k3/Decrypt9WIP/files/650418/seedsave_emu.zip)

**Comment by d0k3** [comment]
Okay, seen it. The seed is in there (once), but the hash verification for it fails. Any chance you modified the installed NCCH?

Anyways, please try to decrypt the CIA in GodMode9 and let me know how that worked for you.

**Comment by MelonGx** [comment]
It's impossible because I never edit it.
I'll try to get the game on another console directly from e-shop and extract the SEED to se if it proper.

**Comment by d0k3** [comment]
I'd still appreciate if you tried GodMode9 (yes, that can decrypt CIAs now, too) ;). If you're afraid of breaking something, use SafeMode9 instead (which also has the CIA decryption stuff).

**Comment by MelonGx** [comment]
I did use GodMode9. That's the result.

**Comment by d0k3** [comment]
Oh, alright. Got it. Is there some public seeddb somewhere? Don't post a link here, but if there is, you could try using this instead, too.

**Comment by MelonGx** [comment]
@d0k3
New console + Directly got this game from e-shop 2 hours ago - One proper SEED of this game can be recognized & Decrypted successfully.
Old console with 48 SEEDs + Repairing this game on e-shop just now - One proper SEED of this game added & Decrypted successfully.

So this case seems to be Nintendo's fault that they distributed broken SEED?

**Comment by d0k3** [comment]
Well, if it keeps on not working on the previous console, you can use the new console to build a proper seeddb. And, well. Nintendo seems to make certain file formats (among them the system save format) deliberately confusing and unintuitive. We don't know everything about the seedsave format, thus our heuristics may fail in some (rare) cases. never experienced it myself, though.
