### ISSUE TITLE
NAND backup identification

### ISSUE THREAD

**Issue by quantumcat1** [d0k3/Decrypt9WIP#128]
I was about to make an issue saying that NAND backups always have a timestamp of 1st March 2016 but then I realised it is because Decrypt9 has no way of knowing what the date or time is.

Can Decrypt9 access the serial number of your device? Would it be possible to add the serial to the naming options?

**Comment by d0k3** [comment]
Not entirely adverse to this, but most people don't own enough different 3DS consoles to justify this. I'll see about this.

**Comment by d0k3** [comment]
Okay, implemented with https://github.com/d0k3/Decrypt9WIP/commit/ad3e33cf273d3e02f22911fc59b27486e9d98e37

User button up/down to select the alternave filename containing the serial.

**Comment by quantumcat1** [comment]
This is fantastically helpful thank you so much :-)
