### ISSUE TITLE
Flaky NTR cartridge connection can lead to nonsensical dump

### ISSUE THREAD

**Issue by izzy84075** [d0k3/Decrypt9WIP#129]
I was going through and dumping my DS cartridges tonight, and one of my cartridges' contacts are pretty heavily worn. It took a couple tries to get it to be recognized as "valid", but the dumping parameters didn't make any sense. It said that the "Cartridge data size" was 0MB, but the "Cartridge used size" was 1558MB, and so the "Cartridge dump size" was also 1558MB.

A sanity check that the cartridge used size is less than the data size might be good.

**Comment by izzy84075** [comment]
CTR cartridges already have this kind of check: https://github.com/d0k3/Decrypt9WIP/blob/master/source/decryptor/game.c#L1957 .

NTR/TWL cartridges don't. https://github.com/d0k3/Decrypt9WIP/blob/master/source/decryptor/game.c#L2160 (Should be somewhere right around there, probably, if it existed.)

**Comment by d0k3** [comment]
Okay, fixed by your own pull request, thank you!
