### ISSUE TITLE
Can't acquire support files

### ISSUE THREAD

**Issue by PKMWM1** [d0k3/Decrypt9WIP#132]
I am trying to modify Pokemon Moon by extracting and encrypting the .3ds. However, it isn't working. It in the README that I need certain support files. However, the support files aren't anywhere in the download and I can't find them a anywhere. If someone could link them for me, I would greatly appreciate it.

**Comment by d0k3** [comment]
Totally wrong place to ask for this. The files you want are copyrighted, so no one on here can help you. Also, a simple Google search would have helped you more than this.
