### ISSUE TITLE
CIA Decryptor (deep): failed!

### ISSUE THREAD

**Issue by seiveXXI** [d0k3/Decrypt9WIP#134]
My issue is that it says the CIA is corrupt or something, i've already read another issues like mine and i think the problem is the seeddb.bin. I think it doesn't have Fire Emblem Special Edition seed, and i can't use seed conv because my 3DS isn't 9.6. I just thought i could get some help here? I need a seeddb.bin that has Fire Emblem Special Edition's seed, so i can decrypt it and that stuff. I think it's the seed because i've tried several seeddb.bin and none worked for me, like none of the seeds have Fire Emblem Special Edition. I don't have the CIA right now so it doesn't give me the exact error as before. But i you really need the ¿log? i could try to get the same error. If you need more information, sorry, my english is limited too, but you can ask!

**Comment by d0k3** [comment]
Two things to try... (1) show me the log, (2) try GM9 (latest release) instead. Do both and let me know the results. Also: don't ask for the seeddb.bin here.

**Comment by seiveXXI** [comment]
Sorry because i'm horribly late, i already used another method, thanks.
