### ISSUE TITLE
Descriptions doesn't fit the lower screen

### ISSUE THREAD

**Issue by GrayJack** [d0k3/Decrypt9WIP#135]
When I hold Y, part of the description is cut in the lower screen.

**Comment by d0k3** [comment]
Can you give me an entry for which that would be the case? Also, damn your fast! Thankyou!

**Comment by GrayJack** [comment]
Pretty much everyone, cause even the ones that the description fit in the screen the parte "For more information, please read github.com/d0k3/Decrypt9WIP/tree/master" and it is cut in the master part

**Comment by d0k3** [comment]
Oh. I just noticed something. You're compiling it not with the standard font, right? In that case, yup, there is not enough room for those descriptions. I guess I will disable it for non standard fonts for now, and think about something later.

**Comment by GrayJack** [comment]
Well I like the original font, it is better for my eyes for some reason, but if that is the problem, then I'll use other font, no problem at all.

Thank you for the fat replies and for your awesome work.

**Comment by d0k3** [comment]
Okay, can you try to compile from this repo and test it?
https://github.com/Wolfvak/Decrypt9WIP
@Wolfvak already did a pull request, and I'll merge it once you say it is okay.

**Comment by d0k3** [comment]
Fixed with https://github.com/d0k3/Decrypt9WIP/commit/0659d93c5ff8001957c7a4fc8a4d84a73d6fabf4

Feel free to reopen if something does not work.
