### ISSUE TITLE
(Suggestion) Decrypt9 WIP Updater As CIA

### ISSUE THREAD

**Issue by MKWPlayer1337** [d0k3/Decrypt9WIP#139]
As title says. Idk if this will be possible or not. Maybe if you could build a cia and then have the user specify options like where to store the .bin file on the SD card and/or specify the name of the file, all in a separate .cfg configuration file. Luma3DS updater has this already implemented for user configurations and such. This may work I think by checking to see if any updates are available from a specific URL, then downloading the .bin file and storing it in your specified location with the specific filename. Also last thing, like Luma3DS Updater, an updater feature for the program itself would be nice. FBI obviously implements this.

Sorry if this is too much to read or if this is not allowed in the issues section even though it's not an issue.

**Comment by d0k3** [comment]
In essence, wrong repo. This is D9, not the D9 updater. D9 being ARM9 software (Luma too, btw), there is no way D9 can update itself (no wifi access).

Check this out:
https://github.com/LiquidFenrir/MultiUpdater
If you can't get it working, or if it just doesn't work, maybe post an issue there?
