### ISSUE TITLE
Help！CTRNAND Transfer.......Region does not match？

### ISSUE THREAD

**Issue by JKC-A9LH** [d0k3/Decrypt9WIP#141]
Region does not match
Using SecureInfo_A from image
In Step 1: Failed, image corrupt or modified!
What's the reason！？Japanese 3DS uses 2.1.0-4J No problem and bin.sha. l put into files9 too

**Comment by d0k3** [comment]
Github issues is not for support. Download the image again and / or get help from the usual places (#3dshacks on Rizon or GBAtemp). Only open an issue here after you made sure the problem is actually in D9.
