### ISSUE TITLE
Changing Name and Banner of App

### ISSUE THREAD

**Issue by Julcello692** [d0k3/Decrypt9WIP#142]
Thank you for Decrypt9, it's great! I'm trying to change the name and banner of Face Raiders without changing its Title ID, since Menuhax only works if the Title ID matches the Face Raiders Title ID. Ideally, I'd like to title it "Menuhax" and have a custom banner if possible. I got my decTitleKeys.bin by going to Titlekey Options and then Titlekey Decrypt. I opened the .bin file in Hex Fiend on Mac, and I can't find the Title ID to replace in the file, nor the hex version of the string "Face Raiders". I found the Title ID for Face Raiders online, but I still couldn't find it anywhere in the file itself. I've attached a screenshot of decTitleKeys.bin dumped just in case that helps. Thanks!

<img width="620" alt="screen shot 2017-01-19 at 8 24 32 pm" src="https://cloud.githubusercontent.com/assets/10580888/22132043/86fb1f1c-de85-11e6-955a-08ebc71ec9f2.png">

**Comment by einstein95** [comment]
The reason why the title does not appear in decTitleKeys.bin is because it does not have the first 0x4 bytes of the title ID set as an eShop title or DLC. decTtileKeys.bin also doesn't have the names of applications, only the title ID and titlekey.

**Comment by Julcello692** [comment]
Thank you, I appreciate your clarifying that. Would you have an idea how I can go about changing the name from "Face Raiders" to "Menuhax" and using a custom banner without changing the title ID, so Menuhax will still work on the same app? I'm just wondering if it's possible.

**Comment by d0k3** [comment]
You're asking in the wrong place, this is not for support or generic development. I'll give you a starting point, tho'. The app name is inside the icon, which is inside the ExeFS partition. The banner is also inside the ExeFS. You may want to try ctrtool (included [here](https://github.com/d0k3/3DS-Tools-Collection)) to extract the NCCH.

With that,  I'm closing this. Use the starting point I gave you, and ask in one of the generic places (GBAtemp / IRC).

**Comment by Julcello692** [comment]
Thank you
