### ISSUE TITLE
Add version to filename when dumping NTR/TWL titles

### ISSUE THREAD

**Issue by einstein95** [d0k3/Decrypt9WIP#143]
https://github.com/d0k3/Decrypt9WIP/blob/master/source/decryptor/game.c#L2129
Adding this feature to this function should me relatively easy. This makes it more in line with wooddumper and would make it more useful to people seeking new revisions of DS games.

**Comment by d0k3** [comment]
Already included with the latest commit.

Test build here:
https://transfer.sh/EpVcc/decrypt9wip-20170120-133100.zip
