### ISSUE TITLE
Unable to dump DLC into CXI

### ISSUE THREAD

**Issue by MelonGx** [d0k3/Decrypt9WIP#146]
No problem with dumping applications (00040000) & patches (0004000e) though.
-----------------------------
Initializing SD card... success
Build: Decrypt9WIP (2017/01/24)
Work directory: /files9
Game directory: /files9
sector0x96 Key: loaded, stored
0x03 KeyX & KeyY: automatically set up
0x25 KeyX: loaded, verified, set up
0x18 KeyX: already set up
0x1B KeyX: not found
0x24 KeyY: automatically set up
Finalizing Initialization...

Initialization: partially failed

Selected: [SD CXI Dumper (SysNAND dir)]
0x34 KeyY: set up from NAND

id0 is (snip)
Use arrow keys and A to choose a folder
/title/0004008c/00190e00

Decrypting CXI from ID 0004008C00190E00
Copying content id 00000065 (72 kB)...
Content not found
0x generated / 1x failed
SD CXI Dumper (SysNAND dir): failed!

Press B to return, START to reboot.

**Comment by urherenow** [comment]
Not that it's your issue, but why the heck wouldn't you take care of your missing key before posting an issue?

**Comment by MelonGx** [comment]
@urherenow  Shut up your smelly mouth it's not 0x1B issue.

Initializing SD card... success
Build: Decrypt9WIP (2017/01/24)
Work directory: /files9
Game directory: /files9
sector0x96 Key: loaded, stored
0x03 KeyX & KeyY: automatically set up
0x25 KeyX: loaded, verified, set up
0x18 KeyX: already set up
0x1B KeyX: loaded, verified, set up
0x24 KeyY: automatically set up
Finalizing Initialization...

Initialization: success!

Selected: [SD CXI Dumper (SysNAND dir)]
0x34 KeyY: set up from NAND

id0 is (snip)
Use arrow keys and A to choose a folder
/title/0004008c/00190e00

Decrypting CXI from ID 0004008C00190E00
Copying content id 00000065 (72 kB)...
Content not found
0x generated / 1x failed
SD CXI Dumper (SysNAND dir): failed!

Press B to return, START to reboot.

**Comment by urherenow** [comment]
That's the first thing I said, but Ifyou want to getnastyandpersomal, I'd be happy to come over, rip off your head, a nd shove it up your ass for you.

**Comment by MelonGx** [comment]
@urherenow The first guy becoming nasty is not me but you. This is not the first time I dislike how you are speaking.
Come on! Just to see who will be fucked up at last. Maybe it's not me, right?

Back to the topic.
If it was 0x1B issue, it would give a response of "Missing xxx file" or similar.
@urherenow I can't imagine a US resident like you can have worse English than a foreigner.

**Comment by urherenow** [comment]
Ok, now that I'm at home with a real keyboard, here's a recap...

Your post included: 0x1B KeyX: not found
^This says you have a missing file

I posted: Not that it's your issue, but 
^ This clearly states that I realize that it's not your issue

Continuing with: why the heck wouldn't you take care of your missing key before posting an issue?

^^ Last, I checked, this was a QUESTION. Not a statement. And a legitimate question at that. If you insist on testing things KNOWING that something is wrong/missing, then your testing skills are useless.

to which you replied: @urherenow Shut up your smelly mouth
^ Personal and nasty. First occurrence here. As opposed to the many nasty ways I could have put my question, but DIDN'T.

**Comment by MelonGx** [comment]
"why the heck wouldn't you" <-- Why your mouth is smelly. Just that simple.

**Comment by urherenow** [comment]
"But via Decrypt9WIP it's convienent" <-- yea... then what's this issue for

**Comment by MelonGx** [comment]
yea... then what's this issue for <-- None of your business.
I'm asking question to d0k3 but not you.
If BLOCKING you could hide everything you posted which makes me unhappy, I would never blaming on you anymore.

**Comment by d0k3** [comment]
Eh, a catfight in my issues section? Is it okay if I interrupt?

Anyways... the missing key also has nothing to do with it. But we already knew, right?

CXI dumping is the wrong choice for DLC. DLC doesn't even contain a CXI, cause it normally is just DLC data + an index file (first content, where the CXI would normally be). Theme packs, f.e., are DLCs.

As to how to get DLC running in Citra, I can't tell... maybe consult their readme or some Citra support place?

Here's two things you could try:
* Build a CIA instead of dumping the CXI. Let me know if it works. Fully decrypted CIAs can be dumped on PC via CTRtool.
* Use GM9 for the job. It's the better tool, promised. In that case select the .TMD via A

Is the file called 00000065.app actually available, btw?

**Comment by MelonGx** [comment]
@d0k3 Thanks for the explaination. I'll back to DLC to CIA & not having any issue on CIA building now.
