### ISSUE TITLE
Decrypt9 Not Loading. 

### ISSUE THREAD

**Issue by meyerjom** [d0k3/Decrypt9WIP#150]
On my 2DS with OLD 11.2.0.35E everything works fine even fasthax goes throug, but after that Decrypt9 will not boot :/
It's not freezing, just goes back to the Homebrew and i could start again.

- Files are up to date.
- i followed the 3ds.guide
& the files have the right name. 
- Also i tried an older release.

**Comment by d0k3** [comment]
This is not a D9 issue and Github issues is not for support. If you updated to 11.3.0, this won't work anymore and you can stop. Otherwise get help at the usual places (#3dshacks on Rizon or temp).

**Comment by meyerjom** [comment]
it was my mistake. Worked now!
