### ISSUE TITLE
Error when creating CIA from DLC

### ISSUE THREAD

**Issue by Targren** [d0k3/Decrypt9WIP#152]
When attempting to build a CIA from an installed title (00040000) or upgrade (0004000e), the CIA Builder works as expected. When trying to build a CIA from a DLC (0004008c), the process fails. 

    Building CIA from ID 0004008C000EDF00
    Fetching TMD...
    Searching for proper ticket...
    Found ticket, injecting...
    Ticket not legit, disabling reencrypt...
    Writing CIA stub (21248 byte)...
    Injecting content id 00000089 (440kb)...
    Content not found
    0x generated / 1x failed
    CIA BUILDER (Sysnand/orig.): failed! 

Steps to reproduce: 

1. Boot into Decrypt9 
2. Select "Content Decryptor Options"->"CIA Builder Options"->CIA Builder (SysNAND/Orig)
3. Select directory under /title/4008c/ directory (e.g. /title/4008c/000edf00) and press A

**Comment by d0k3** [comment]
Can you try again with the most recent nightly from here?
https://d0k3.secretalgorithm.com/

Then let me know if it works.

**Comment by Targren** [comment]
Nope, exact same result

**Comment by d0k3** [comment]
Okay, fix is coming up. In the meantime try building that CIA in GM9 (your installed content is in the A:/ drive, press the A button on the content TMD).

**Comment by d0k3** [comment]
Also, try this D9 test build and tell me if it is solved for you:
https://transfer.sh/Kb6TH/decrypt9wip-20170214-113244.zip

**Comment by Targren** [comment]
Thanks. The new test build seems to have solved it, and GM9 also worked.

**Comment by d0k3** [comment]
Fixed in https://github.com/d0k3/Decrypt9WIP/commit/8e5f223998ccb114a19df38dc5244ff86acf1ba6
