### ISSUE TITLE
Digital game dump to .3DS.

### ISSUE THREAD

**Issue by vonKoenigsberg** [d0k3/Decrypt9WIP#154]
Since Hourglass9 can dump digital games to .CIA, I'd say it would suit decrypt to have a feature to dump digital games to .3DS, as it is the more mature dump method for people who have a pc and who want to build up an emulator library.

**Comment by ihaveamac** [comment]
you can dump digital games to decrypted cxi and use those in citra if you want to use it in that. as far as I know there's no real need for ".3ds" dump except for Gateway.

**Comment by vonKoenigsberg** [comment]
Cxi is an ugly incomplete format.

**Comment by ihaveamac** [comment]
cxi is not an "ugly incomplete format". ".3ds"/cci is just a container of cxi and cfa files. it will perform exactly the same. unless you mean braindump which can't access everything to create a complete cxi.

**Comment by vonKoenigsberg** [comment]
No cfa files means no update files means incomplete and ugly.

**Comment by vonKoenigsberg** [comment]
Aside from that, how do you create a cxi from digitals with decrypt?

**Comment by Zetchzie** [comment]
as much as id love this feature id prefure a new way to find and choose your titles so i know what i'm selecting. I have to go to FBI and look at the games ID and write it down then go into decrypt and find it lol

**Comment by ihaveamac** [comment]
"No cfa files means no update files means incomplete and ugly." what? the extra cfa files don't affect the game itself (manual, dlpchild). cxi is what matters.

"Aside from that, how do you create a cxi from digitals with decrypt?" Content Decrypt Options -> SD File Options... -> SD CXI Dumper (SysNAND dir) - GodMode9 also does this (under SYSNAND SD)

**Comment by d0k3** [comment]
Aw, come on... What would you like to use that .3DS for? GW?

You're also missing a few important points here. (1) Digital downloads have no update data. Why? Cause you can only use the eShop if you are on the most recent system version. And, no, Nintendo does not care about freeShop users. (2) No, I can't just build a valid NCSD (".3DS") file out of thin air. NCSDs are signature protected. This is also the reason why such NCSDs would never run on anything like the Sky3DS. (3) If you are a collector, a CIA is actually more genuine than a "bastardized" NCSD, cause the CIA actually consists of all the files fyou downloaded.

If it is for GW, I decided a while ago not to do any workarounds or GW compatibility stuff anymore. If it's for collecting purposes, get a valid cart dump.

Hope that settles it, closing it now.

**Comment by urherenow** [comment]
umm... the OP says it's for future emulators; doesn't mention Gateway.

**Comment by d0k3** [comment]
What I wrote still stands. I'm a digital preservation advocate myself, but in times of digital downloads, future emulators have to handle digital download formats (aka CIA) as well as physical cart dumps. We can't just Frankenconvert everything into one specific format.

Besides - it would be pretty easy to "teach" any emulator to grab the CXI directly from a CIA file.

**Comment by vonKoenigsberg** [comment]
Thanks for clarification.
