### ISSUE TITLE
FBI injection not work

### ISSUE THREAD

**Issue by Starboltz** [d0k3/Decrypt9WIP#155]
Hi everyone, i downgraded my 3ds with GW, but when i follow the troubleshooting, i have 2 files of .tmd(lowcase and upper) and only one .app(uppercase), when i use the pair of lowcase, not work, open health & safety, when a switch the .app, leaving the .tmd lowcase and de .app uppercase, says that is corrupted or something like that....any thoughts? thanks guys!

**Comment by d0k3** [comment]
Github issues is not for support. There is something wrong in your system and you need to fix it. Search help in the usual places (@Plailect's guide, #3dshacks on Rizon). You may also try H&S injection via GodMode9 (recent build from d0k3.secretalgorithm.com, consult teh readme).
