### ISSUE TITLE
DSi header 128 MB+ DS dumps have underdumped header

### ISSUE THREAD

**Issue by PPLToast** [d0k3/Decrypt9WIP#157]
When dumping any DS cart on Decrypt9 that is 128 MB or over and released after ~2009, the header is underdumped which results in a bad dump. The hashes are similar to older bad scene dumps for games like Spirit Tracks, Kirby Super Star Ultra, Kingdom Hearts - 358-2 Days and the like.

**Comment by d0k3** [comment]
Alright, can you tell me what you mean by underdumped header? Is there data missing from it? Also, pls try it in GM9, too, and report back about the results.

**Comment by PPLToast** [comment]
Ah damn, just gave it a try again (both GM9 and D9) and its working properly now. Not sure when this was fixed, but my bad.

But yeah basically NTR+TWL type cards had parts of their header completely missing before. http://i.imgur.com/Hw32Lc5.png
http://i.imgur.com/8b30BjP.png

**Comment by d0k3** [comment]
Well... must have been fixed somewhere in between. Closing this now...
