### ISSUE TITLE
[SUGGESTION] Dumping NTR/TWL cartridges to .cia

### ISSUE THREAD

**Issue by infinity5** [d0k3/Decrypt9WIP#158]
I have many DS cartridges (TWL) that I want to dump to a .cia file so that I can install the backup on my system. However when I try to select (Dump Cart to CIA) it fails saying (NTR/TWL cartridges cannot be dumped to CIA.) I know this is normal, but I want some functionality that will at least give me a dump, even if it is not perfect. Could you please incorporate this?

**Comment by GerbilSoft** [comment]
What would be the point? Even if an option was added to embed an SRL in a CIA (i.e. DSiWare), it wouldn't run. You'd end up with either a white screen or an error message.

**Comment by d0k3** [comment]
What @GerbilSoft just said. DSiWare (SRL) is not the same as a NDS rom dump. There really is no reasoning in dumping such a cart to a CIA. So... Anything you could add to this?

**Comment by d0k3** [comment]
Alright, closing this now. Feel free to reopen if you can add anything to this.

As said before, such a CIA dump would not be imperfect, it would be just wrong and never work. If it would, we wouldn't have efforts such as nds-bootstrap and TWLoader.

**Comment by infinity5** [comment]
I used TWLoader and it worked for me. I just never knew about these applications before so I couldn't use them ;)

**Comment by d0k3** [comment]
Adding to this, even if it is closed - if nds-bootstrap ever reaches a decent state, yes, NDS rom CIAs may become a reality. But then in the style of VC CIAs, meaning that they wouldn't be ran directly but instead handed over to nds-bootstrap.
