### ISSUE TITLE
Dumping updates and merging them with the base game/making use of them in Citra.

### ISSUE THREAD

**Issue by vonKoenigsberg** [d0k3/Decrypt9WIP#159]
How would one dump game updates with decrypt and get them to work with Citra? Is there a way to create a merged file with updates and base game?

**Comment by vonKoenigsberg** [comment]
And if I dumped my games previously and installed them then digitally as cias, do these games them have separate update data like cartridge games or are they complete updates like digitals?

**Comment by urherenow** [comment]
GitHub isn't a forum; not the place for this question. Digital or cart doesn't matter. All update files go to SD, and only files that are updated.

**Comment by d0k3** [comment]
Maybe, what you want to do is possible makerom and ctrtool and the dumped CXIs. Still, this is the wrong place to aks. Github issues is not a forum.

**Comment by vonKoenigsberg** [comment]
Yeah, but can one even dump the updates with decrypt? The merge was just a follow-up question.
