### ISSUE TITLE
Bug download

### ISSUE THREAD

**Issue by adriih123123** [d0k3/Decrypt9WIP#160]
Hello guys

I can't dowload decrypt9wip, fasthax and fasthax :((

why ?

**Comment by GerbilSoft** [comment]
What happens when you go to the Releases tab and try to download a release?

https://github.com/d0k3/Decrypt9WIP/releases

**Comment by DVonk** [comment]
Got the same problem. All three release pages give a timeout error when trying to download the built files. Source code can be downloaded without problem.

This is the error message that comes after a few seconds when I try to click the links (freely translated from German):
The server under github-cloud.s3.amazonaws.com took to long to respond.

**Comment by GerbilSoft** [comment]
Amazon S3 is currently experiencing an outage.

https://tech.slashdot.org/story/17/02/28/1854232/amazons-cloud-service-has-outage-disrupting-sites

**Comment by d0k3** [comment]
That's not a D9 bug, that's a Amazon / Github bug. Closed.
