### ISSUE TITLE
How can i check which version of bootloader have my AK2i ?

### ISSUE THREAD

**Issue by the4anoni** [d0k3/Decrypt9WIP#163]
What icon i launcher should i have for 1.41 version ? Currency i have Pippa Funnel (Ubisoft). Afaik this is unfinished beta FW.

**Comment by d3m3vilurr** [comment]
technically possible. but i don't know finding firm version value from bootloader.
but can search game id instead this.

anyway 1.41 will print Alex Rider. Pippa Funnel probably 1.44 version

https://wiki.gbatemp.net/wiki/Updating_the_AK2i_Bootloader#Before_you_begin

**Comment by the4anoni** [comment]
I downloaded 1.41 FW from here ,but it shows me title Acekard 2i www.acekard.com istead of Alex rider

**Comment by the4anoni** [comment]
OUCH flashcard wont start on luma 11.3....... Error has occured.... Ok will update back to the Pippa Funnel

**Comment by d3m3vilurr** [comment]
Ah, right. 1.41 bootrom probably show AK2i on 3DS.
I mean, each version's bootrom have diff game id, and these values can use for detecting version.
BTW, in before, I only checked 1.41 and 1.44 :/

PS. I'm not tested with 11.3. but if you use apache thunder's NTR launcher, probably work.
(at least, work well on 11.2)

**Comment by the4anoni** [comment]
Restored sucesfully to Pippa Funell :)

**Comment by d0k3** [comment]
Looks solved, closing this now.
