### ISSUE TITLE
Homebrew/Safehax/D9Wip ends in "Initialization failed"

### ISSUE THREAD

**Issue by BWonder** [d0k3/Decrypt9WIP#166]
I wanted to make a backup of my NAND (V11.0.0-33E)
Homebrew was already installed to play some legit cia's and homebrew games.
So i added Safehax and Decrypt9Wip (exact as on the https://3ds.guide/decrypt9-(homebrew-launcher)) page.
Next in my homebrew i do fasthax followed by safehax.
I always end up with:
-- Decrypt9WIP (2017/02/25) --
Counting 30 submenus and 165 features
Initializing, hold L+R to pause
Initializing SD card... failed
Initialization: failed!
(A to exit)

As a user i can't do much wrong i think. For the moment i just want a backup on my NAND (as this one can still be downgraded and 11.3.0 not at the moment)

**Comment by d0k3** [comment]
This looks like a problem with your SD card... before you do anything else, tho, try two things:

1. Use the latest D9 hourly from https://d0k3.secretalgorithm.com/
2. Try GM9 from https://d0k3.secretalgorithm.com/ instead - can you access your SD card with it?

**Comment by BWonder** [comment]
Thanks for the response:
1) Tested the D9 hourly: Decrypt9WIP-20170317-184616.zip
-- Decrypt9WIP (2017/03/17) --
Counting 30 submenus and 165 features
Initializing, hold L+R to pause
Initializing SD card... failed
Initialization: failed!
(A to exit)
- Result is exactly the same

2) Tested the GM9 hourly: GodMode9-20170320-040159.zip
(copy and rename GodMode9.bin to safehaxpayload.bin (root))
Both screens turn black and stay black

placed the D9 and GM9 Directorty ( with *.3dsx files) in 3DS dir to see if they run from homebrew.
No luck, both turn black (and red) shortly and return to homebrew.

Final a last attempt (only deleted safehaxpayload.old.bin (temp rename))
However 2nd time:
Godmode9 Explorer V1.0.5
Don't know what to do but -> R+B = Remount SD card
"Initialising SD card failed! Retry?"
Endless <A> keeps saying the same.

(on exit when trying to format it says "Format SD card (122160MB)?" -> right size i got a 128GByte

Then if i try FBI to install one of  the not installed legit CIA's from SD (to SD of course)
Everything works? In FBI i can walk though the directories and do everything.

System: N3DSXL-EU V11.0.0-33E
No: Nintendo connection (wifi normal off and device blocked by router) (no NNID or shop account)
SD-Card: 128GB  (Samsung MicroSDXC 128GB EVO Plus UHS-I Grade 1 Class 10)
All installed legit CIA's work from SD
Before usage SD card was tested with h2testw (that was however 2 months ago)

Any suggestions?

**Comment by d0k3** [comment]
Well... SD cards in the 3DS are a fickle thing. In general, I recommend using GM9 for formatting the SD card. Now, I know it's no fun to backup, format and restore a 128GB SD card, but that's actually what's best to do in that case.

**Comment by BWonder** [comment]
I will backup, also try a 2nd card and format with GM9 this weekend to see if i can get a backup, i will leave the result here.

**Comment by d0k3** [comment]
There has been no additional information to this issue for a long time, so I'm assuming it being fixed.
