### ISSUE TITLE
is this my fault?

### ISSUE THREAD

**Issue by mannworker** [d0k3/Decrypt9WIP#167]
i try use fasthax then safehax but the screen is always black did i do something wrong?

1. i got homebrew working using soundhax
2. iv put "Decrypt9WIP.bin"(and only that) in the sd card and renamed it "safehaxpayload.bin"
3. fasthax works but when i start safehax= blackscreen

i have a game cart in the 3ds to

**Comment by d0k3** [comment]
Try the latest hourly build of Decrypt9 from here:
https://d0k3.secretalgorithm.com/

Then tell me if that works for you.

**Comment by d0k3** [comment]
@mannworker - if it still does not work, I need more info. If it does, let me know, so I can close this issue.

**Comment by d0k3** [comment]
Assuming working now, closing this. Feel free to reopen.
