### ISSUE TITLE
Can't Dump Home Menu DLC

### ISSUE THREAD

**Issue by gudenau** [d0k3/Decrypt9WIP#169]
When attempting to dump titles 0004008C00008F00 or 0004008C00008F01 D9WIP complains about missing content.

> Selected: [CIA Builder (SysNAND/orig.)]
> 0x34 KeyY: set up from NAND
> 
> <id0> id XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> User arrow keys and <A> to choose a folder
> /title/0004008x/00008f00
> 
> Building CIA from ID 0004008C00008F00
> Fetching TMD...
> Searching for proper ticket...
> Found ticket, injecting...
> Console unique info found, wiping...
> Ticket not legit, disabling reencrypt...
> Writing CIA stub (27712 byte)...
> Injecting content id 00000142 (1524 kB)...
> Decrypting content id 00000142 (SD)...
> Injecting content id 00000001 (3296 kB)...
> Content not found
> 0x generated / 1x failed
> CIA Builder (SysNAND/orig.): failed!
> 
> Press B to return, START to reboot.

**Comment by d0k3** [comment]
That's a known issue, because DLC (gotten through legit means) almost never is complete (and, yes, not even if you purchase it all). The fix for this would require bigger changes, so I may or may not do it later. Use GodMode9 instead.
