### ISSUE TITLE
Ability to not dump a file to CIA/CXI if it already exists

### ISSUE THREAD

**Issue by deadair3210** [d0k3/Decrypt9WIP#170]
Exactly what it says on the tin, not sure but I think Decrypt9 currently overwrites files without any checking, if I'm wrong, sorry in advance and feel free to close this. Would be nice to notice that the file already exists and skip dumping that title

**Comment by d0k3** [comment]
I'm thinking about this, but most likely this won't be fixed. GodMode9 has all of the advanced handling and flexibility that you will need now, and D9WIP is limited by it's dated codebase / by it's interface.

**Comment by deadair3210** [comment]
Does GodMode9 have this feature or does it overwrite files as well? If so, i might just work on adapting my procedure to use GodMode9 instead of Decrypt9

**Comment by d0k3** [comment]
Well... GodMode9 allows you to select which files to process. If what you want to do is just select them all and autoskip those that already exist, that does not work atm. I can implement that, if you convince me, though.

**Comment by deadair3210** [comment]
I am trying to dump all the titles on my 3ds so that i can try them with things like citra, but obviously this is going to take a while so i dont want to do it  all at once. it would be awesome to be able to set which ones that i want to decrypt and then have godmode9 dump them if it needs to, or skip it if it already exists
