### ISSUE TITLE
.firm version for latest Luma?

### ISSUE THREAD

**Issue by ewormPL** [d0k3/Decrypt9WIP#172]
As of version 7.1 Luma3DS no longer launches .bin payloads, instead opting for .firm support with boot9strap. Would a compatible version of Decrypt9WIP be possible?

**Comment by xGhostBoyx** [comment]
I'd also appreciate an update here. I understand Decrypt9 is not something that will be supported in the future, but it is however extremely useful for doing certain things very fast. It's also very noob friendly when explaining certain things to people (as someone who helps on the discord).

**Comment by ewormPL** [comment]
Woop, I found a converted version that seems to be working fine [here](https://gbatemp.net/threads/tutorial-how-to-convert-arm9loaderhax-payloads-to-firms.471144/page-2#post-7320013).

Though I'd still appreciate an official one with everything tested and all that.

**Comment by d0k3** [comment]
Already done, don't be so impatient ;).
