### ISSUE TITLE
Content Decryptor, CIA Builder Game directory not found

### ISSUE THREAD

**Issue by wicksand420** [d0k3/Decrypt9WIP#173]
Selected:  [CIA Builder  (SysNAND/orig.)]
Game directory not found!
(check readme for more info)
CIA Builder  (SysNAND/orig.):  failed!

Decrypt9WIP-20170520-112511 is the newest
it is the .firm version of decrypt9 and i am on luma 11.4 on o3dsxl with sighax installed.

**Comment by wicksand420** [comment]
When updating to sighax we where told to erase the files9 folder. this was the problem.

**Comment by Jerry-Shaw** [comment]
Yep, the "files9" is for D9/E9/G9, not for Luma. So the guide told us to delete it when sighax is installed. But if you still use D9/E9/G9, keep it.
