### ISSUE TITLE
System Info Bug

### ISSUE THREAD

**Issue by SerraraFluttershy** [d0k3/Decrypt9WIP#175]
I am running Decrypt9 under boot9strap, yet under System Info it reads:
 "Running from arm9loaderhax: yes"
even though this is the .FIRM payload. 
![arcsoft_image111](https://cloud.githubusercontent.com/assets/23690950/26684389/787bd42e-46ac-11e7-8c12-36df524b8511.jpg)

**Comment by ihaveamac** [comment]
#174
