### ISSUE TITLE
Update to work with B9S 1.1/1.2?

### ISSUE THREAD

**Issue by Zalexard** [d0k3/Decrypt9WIP#176]
I know you said we should be using GM9, but are you going to show some more love and update D9 to work with the newest releases of B9S? Thanks for all the work! :)

**Comment by d0k3** [comment]
It's actually easily done, see here:
https://github.com/d0k3/GodMode9/commit/d8d2901ec1b125fdb36e2c728cfa8e84f9bc13f3
https://github.com/d0k3/GodMode9/commit/540daed73a7672fbdfe061675bba8f3c6920c573

I do take pull requests, otherwise it's when / if I get to it.

**Comment by Zalexard** [comment]
Sure thing, was just curious if you were going to do something with it. I'll try my hand at this later, looks pretty foreign to me but I should be able to scratch something out eventually. :D

**Comment by Freeglobe** [comment]
i hope, a new version will release soon. :-)
