### ISSUE TITLE
Decrypt9 won't boot

### ISSUE THREAD

**Issue by PlasticJustice** [d0k3/Decrypt9WIP#177]
Whenever I try to use Decrypt9, it gives me the error in the image below.
![2017-06-05 01 44 20](https://cloud.githubusercontent.com/assets/8683689/26773483/11b97952-4991-11e7-8c70-20a49df26c4c.jpg)

**Comment by james-d-elliott** [comment]
https://twitter.com/SciresM/status/871517702778757120

**Comment by PlasticJustice** [comment]
thanks. that worked.
