### ISSUE TITLE
Can't convert .3ds to .cia anymore

### ISSUE THREAD

**Issue by Constoush** [d0k3/Decrypt9WIP#181]
I don't know why but with the new version of Decrypt9, there's no way to convert 3ds files to cia directly from my 3DS, maybe this feature has been deleted, but it's a huge problem for me... Can't convert my 3ds files as easylly as I did..

**Comment by d0k3** [comment]
Nothing has changed re that feature. A 3DS file is a NCSD file if that helps. Also, use GodMode9.
