### ISSUE TITLE
Error while dumping downloaded DLC

### ISSUE THREAD

**Issue by willstr88** [d0k3/Decrypt9WIP#183]
When I try to dump the DLC from Fire Emblem Fates: Special Edition, it gives me this:

Fetching TMD...
Failed building the CIA stub
0x generated / 1x failed
CIA Builder (SysNAND/decr.): failed!

Why is this? The actual game dumps fine.

**Comment by MelonGx** [comment]
D9WIP can't dump incomplete DLC.
If you want to dump that, use GM9 -> [A:] SYSNAND SD -> title -> 0004008c -> (Your game ID) -> content -> Choose the .TMD file -> TMD file options... -> Build CIA (standard).

**Comment by d0k3** [comment]
What @MelonGx said.
