### ISSUE TITLE
Split ROM decryption

### ISSUE THREAD

**Issue by gudenau** [d0k3/Decrypt9WIP#19]
I would like it if you could decrypt split 3DS rom files.

For the moment I will work on this, but if someone beats me to it I will be OK.

**Comment by d0k3** [comment]
Providing this functionality would require a 'wrapper' FileRead() function that processes multiple split parts as one file. This is not simple to do at all and one would have to be extra careful not to break anything else in the process.

So, is this really useful? Afaik, there is no rom so far > 2GB, meaning that the split feature is not required at all (roms of exactly 2GB can be trimmed by one byte). Also, the only piece of hardware / software that really supports these splitted roms at this time is GW (again, as far as I know), and GW doesn't really like fully decrypted roms.

**Comment by gudenau** [comment]
Xeno is 4GB. I am aware that this can break stuff in weird and wonderful ways, I will try to be careful.

**Comment by d0k3** [comment]
I just saw, the true limit is at 4GB for FAT32... so Xenogear Chronicles could still be decrypted even now if it is trimmed by at least one byte. Don't know if it's really worth the effort, but if you intend to do a pull request keep the changes as minimal and as separate to the existing code as possible.

**Comment by gudenau** [comment]
That is the idea, I am planning on just checking the extension; if it is
split use a diffrent method to decrypt it.

**Comment by einstein95** [comment]
There's 24 games that use a 4GB cart, you can see which by going to http://3dsdb.com/ and searching for 32768

**Comment by d0k3** [comment]
Still, as I said, trimming these files by just one byte will enable current Decrypt9 to process these files on FAT32, while enabling split rom decryption might break things.

**Comment by d0k3** [comment]
@gudenau @einstein95 is there still any interest in this? Otherwise I'd close it.

**Comment by tetsuo55** [comment]
Do we know if that 1 byte always contains garbage or padded data?
Could it be that we are losing data by trimming it?

For accurate dumping of 3ds carts we would have to be sure.
One simple option could be to keep on dumping after the limit is reached into a 2nd file.

Merging the files would have to be done on pc by the dumper.

**Comment by d0k3** [comment]
D9 checks if that byte contains data or not. This was never the case, is very improbable, and will most likely never happen.

**Comment by g6672D** [comment]
It's actually losing 512 bytes, also whereabouts does it check that the truncated part is just padding?

https://github.com/d0k3/Decrypt9WIP/blob/master/source/decryptor/game.c#L1983

Assuming it isn't losing actual data, can the program at least print a warning that it will need to be fixed before hashing?

**Comment by d0k3** [comment]
You could have looked just a little bit above:
https://github.com/d0k3/Decrypt9WIP/blob/master/source/decryptor/game.c#L1982

Research on 3dbrew (topic: NCSD) if you want to know why this works. I agree that a quick debug output about removing the last sector makes sense.

**Comment by g6672D** [comment]
Doesn't that just tell you the space is unpartitioned and not what's actually stored in the cartridge? Yes those regions should be 0xFF but the whole point of doing full cartridge is on the vague chance that it's not.

**Comment by d0k3** [comment]
Well...

We've only got a handful of cartridges with 4GB size. None of these contain any data beyound the actual used space (actually there is not a single known case with 'hidden' data on any 3DS cartridge). Split dumps would be  major annoyance - for me, to implement, and for the user to handle. Also, if you absolutely need split dumps, you can use uncart or GW software.

Besides - you would be better off writing some application that actually searches for that 'hidden' data if that's what you'd be after.

**Comment by g6672D** [comment]
No problem. I'll attempt to hack my own check into decrypt9, that'll be enough for me. Thanks for adding the warning message and for your input.
