### ISSUE TITLE
MultiNAND support?

### ISSUE THREAD

**Issue by Ketchup901** [d0k3/Decrypt9WIP#21]
Is there a way to pick a 2nd/3rd/4th emuNAND from Decrypt9?
If so, how?
If not, could you implement it?

Thanks.

**Comment by d0k3** [comment]
Try this Decrypt9 fork:
https://github.com/LinkeneitoR/Decrypt9/releases

I'm currently considerung adding this functionality into the main release.

**Comment by Ketchup901** [comment]
Sweet, thanks!

**Comment by d0k3** [comment]
Added in https://github.com/d0k3/Decrypt9WIP/commit/40912da6b85e3a77031380d9bec11fd500a9c936
