### ISSUE TITLE
Option to make a noise when decrypt/dump/etc complete?

### ISSUE THREAD

**Issue by JixunMoe** [d0k3/Decrypt9WIP#23]
Some dump/decrypt function took a lot of time (backup nands, generate nand pad etc), would be great if Decrypt9 can make a noise (or an audio file) when is done.

Thanks.

**Comment by d0k3** [comment]
Not possible on ARM9 (and will most likely never be, sorry). It would be a nice idea, though. CLosing this for now...

**Comment by JixunMoe** [comment]
OK, thanks for answering :D
