### ISSUE TITLE
Selftest gives false positive on ncch_7x_key and nand_twl_key

### ISSUE THREAD

**Issue by dogtopus** [d0k3/Decrypt9WIP#31]
Both of them actually work correctly on both a9lh and hblauncher (which is known to work)

**Comment by d0k3** [comment]
That is not a false positive, but the expected result on A9LH. We're trying these keys without setting them up before.

D9 has a workaround for both - the TWL key is calculated internally and the 7x key is provided by you via the slot0x25keyX.bin file.
