### ISSUE TITLE
Restoring Proper NAND Backup Failed

### ISSUE THREAD

**Issue by sora10pls** [d0k3/Decrypt9WIP#32]
I was having some trouble restoring a proper NAND backup due to the file extension. The file name was NAND.BIN and wasn't deemed usable by Decrypt9. However, once I renamed it to NAND.bin, it worked perfectly fine. It should be case insensitive.

**Comment by d0k3** [comment]
You are right. Will fix that later.

**Comment by MelonGx** [comment]
It's very interesting that .BIN cannot be recognized but .bin can.

**Comment by d0k3** [comment]
Actually it is not. Simple strncmp() instead of strcasecmp() ;).

**Comment by d0k3** [comment]
Fixed in https://github.com/d0k3/Decrypt9WIP/commit/60d460502aff47fef71a2fc2d9c75049e57c5b14 - maybe you can test if it works for you, too?
