### ISSUE TITLE
Unmouting SD: Windows want to format it

### ISSUE THREAD

**Issue by mariogamer2** [d0k3/Decrypt9WIP#34]
How to reproduce:

Simply unmount SD and plug it into a Windows PC,it will say you that you have to format it...

(not on linux, don't know for mac...)

**Comment by d0k3** [comment]
Umm... What happened? Why did you close it? :)

**Comment by mariogamer2** [comment]
Don't know if the issues is always ok,just re-tested it work fine...

**Comment by d0k3** [comment]
I think this is a Windows issue, not one of D9. Seen this happen without D9, too.

**Comment by MelonGx** [comment]
- Buy a high quality SD reader
- Check your USB port's power supply (especially your front USB ports)

**Comment by mariogamer2** [comment]
My SD card is working very fine on linux so...

In fact,I'm more using linux than windows,I jhust created the issues for other people :)
