### ISSUE TITLE
Blue Screen Error A9LH

### ISSUE THREAD

**Issue by Zetchzie** [d0k3/Decrypt9WIP#36]
I try to launch the latest build as of 3/31/16 and get a Blue Screen with random numbers And Bootrom error im on N3DS, A9LH, A9Select, and sysnand 10.7

**Comment by Zetchzie** [comment]
glad its not user error then i thought i bricked aswell lol

**Comment by Zetchzie** [comment]
Sorry on my Vita i pressed close and coment instead of just coment.

**Comment by d0k3** [comment]
Goddammit, hundreds of bricks and counting! I shouldn't have just copy-pasted that bootrom dumper code, but that guy seemed legit.

**Comment by Shadowtrance** [comment]
bahahaha! yep that's all i have to say. lol

**Comment by TheBaloneyboy** [comment]
Fixed in latest release
