### ISSUE TITLE
Multi EmuNAND detection is broken on O3DS

### ISSUE THREAD

**Issue by pcm720** [d0k3/Decrypt9WIP#37]
3072e0a broke multi EmuNAND detection on O3DS. 
The error is in line 17 of source/decryptor/nand.c:
`#define EMUNAND_MULTI_SECTORS ((getMMCDevice(0)->total_size >= 0x200000) ? 0x200000 : 0x400000)`
It sets `EMUNAND_MULTI_SECTORS` to `0x400000` instead of `0x200000`.

I'm pretty sure it should look like this:
`#define EMUNAND_MULTI_SECTORS ((getMMCDevice(0)->total_size > 0x200000) ? 0x400000 : 0x200000)`

**Comment by d0k3** [comment]
Fixed with the last commit, thank you!
