### ISSUE TITLE
Stalling at Initializing SD card... success

### ISSUE THREAD

**Issue by deadair3210** [d0k3/Decrypt9WIP#38]
Downloaded latest build (2016/04/01), and launching the Gateway entrypoint on a old 3DS XL 9.2 sysNAND, cant get the program to proceed past Initializing SD card ... success. Have tried it 3 times, with no change.

All that prints out is
Decrypt9WIP (2016/04/01)
Counting 15 submenus and 111 new features
Initializing, hold L+R to pause

Initializing SD card ... success

**Comment by d0k3** [comment]
Three things you can try (in order of chances of success):
* Use CakeHax instead of GW (see the readme for instructions).
* Put the d9logo.bin on the root of your SD card
* Try another SD card or format this one

**Comment by deadair3210** [comment]
I will try these as soon as I get a chance. Would it be of any help if i told you that it was a 32 GB card

**Comment by deadair3210** [comment]
Just got it to work with CakeHax, and d9logo.bin at the root. Is there anything I can do to help you figure out why its not working through Gateway?

**Comment by d0k3** [comment]
I will think about it and come back later. I'll also leave that open for now. Thanks for offering help, too!

**Comment by deadair3210** [comment]
No problem

**Comment by d0k3** [comment]
You could try if CakeHax works without the d9logo.bin (it should!). I'll also see about providing a test build that will fix the GW entrypoint later.

**Comment by deadair3210** [comment]
GW doesnt work with or without d9logo.bin. CakeHax still works without d9logo

**Comment by d0k3** [comment]
Alright, thank you! I do have a test build now, which might fix the issue... could you try?
https://up1.ca/#rW7vcFlksw73zZOXA8eoRQ

**Comment by deadair3210** [comment]
Nope, no change through Gateway. Still stuck at initializing sd card

**Comment by d0k3** [comment]
I just came up with something else that you can try:
https://github.com/d0k3/GodMode9/releases

You don't have to use the Sys-/EmuNAND writing features, as long as the top bar is green, the write permissions for that are disabled. You only need to start it via the GW Launcher.dat and try to move around some files. If that works, I already learned a lot about what causes this bug.

**Comment by deadair3210** [comment]
If I get far enough to see the menu options, it will be farther than it has gotten before. Will try this when I get out of class later today

**Comment by deadair3210** [comment]
Got out early, tested the program. Nothing was printed to the screen at all this time. 

Procedure
1. Boot into 9.2 sysNAND
2. Open browser
3. Go to go.gateway-3ds.com
4. Gateway 3DS loading
5. Screen Wipe to white
6. Screen turns black with backlight on and never changes

With Decrypt9WIP it at least got to attempting to access the SD card

**Comment by d0k3** [comment]
You did everything right from what I see, and I already have an idea on what could cause this. There are 2 more things you could try (then I have  at least limited the possibilities down to a few):
* Try OTPHelper. It should boot properly, but as soon as you try generating the FIRM0FIRM1 XORpad it should freeze. (it will freeze with others, too, FIRM0FIRM1 XORpad is just the quickest non-intrusive option)
* Try EmuNAND9. There should be no problems with this at all, but just to be safe you could try creating a SysNAND backup with it.

Also, thanks a lot for your help! It is not easy finding a tester with the exact right setup.

**Comment by deadair3210** [comment]
I will try these when I get a chance, although it might not be tonight as I will be busy with other things

No Problem helping, I understand how hard it is to test a program when you only have so many environments you can test it in. Plus I'm learning to program, so it lets me learn

**Comment by deadair3210** [comment]
OTPHelper launched correctly, and froze during padgen, and EmuNAND9 successfully made a sysNAND backup. Good news?

**Comment by d0k3** [comment]
Okay, thank you and sorry for the radio silence. I do know now - almost for sure - what causes this. Problem is: this is not easily fixable. As CakeHax works for basically all old GW Launcher.dat users, I'm considering now to just give that entrypoint up.

Before that decision is final, there is one more thing that you can try from the GW Launcher.dat entrypoint:
https://up1.ca/#Svq1VYGIXxUSQrkwb0BETQ
This is a new GodMode9 test build, and I'm only interested in wether this boots up from GW Launcher.dat. When you have time, and again, thank you!

**Comment by deadair3210** [comment]
Unfortunately the build never boots, the 3DS never gets past the black screen after the screen glitch.
May I ask what the problem is, I'm curious and actually trying to get into programming

**Comment by d0k3** [comment]
Alright, I'll try to explain... With arm9loaderhax, we had to change some stuff. Arm9loaderhax is special in that it works as entrypoint before the system has actually full started, meaning some stuff is not set up yet and we need to do it ourselves now. For decryption to work for certain NAND regions (the TWL ones in that case) we need access to [certain memory regions](http://3dbrew.org/wiki/Memory_layout#ARM9_ITCM).

Now, that access doesn't come for free, we actually have to set it up (that's done in the bs-start.s / gw-start.s files in my case) and sometimes there is trouble, as with the GW Launcher.dat entrypoint. That entrypoint crashes whenever we try to access ITCM.

The solution in the case of GW Launcher.dat is: Disable the access to ITCM - we don't need it for the GW entrypoint. If you want to know what is different now, take a look here (last commit):
https://github.com/d0k3/GodMode9/commits/new_ep_setup

And, I know, I said it is not easily fixable, and that decision to ditch the entrypoint is final. I did have an idea, though (the last commit you saw above), and thus there is a new test build:
https://up1.ca/#gYuli_oHpZ_xN-iX5hcFtQ

Could you try this one on GW Launcher.dat and one CakeHax? There is something changed for both, so I need to know if it works.

Also, if you want to get into programming, better start with the [easy stuff](https://github.com/d0k3/HelloEntryPoint). It may not even be a good idea to start with ARM9 programming, as it is more difficult than ARM11 programming with ctrulib.

**Comment by deadair3210** [comment]
With the ITCM access disabled, it seems to boot correctly on Gateway, but CakeHax fails to boot

Thank you for explaining, I have been trying to learn as much as I can about the 3DS, and how it operates at a low level. I have been thinking about trying to set up my 3SD for arm9loaderhax but haven't mustered up the courage to do so, finding no issue with using menuhax + rxTools.

**Comment by d0k3** [comment]
Okay, thanks a ton!

This test build should work on both, Launcher.dat and CakeHax.dat:
https://up1.ca/#HORPtln723TICPrAk7sBiA

Could you try? If that works, it is the last one, promised.

Btw, if you are interested in learning stuff (and testing bleeding edge stuff), you can join us on freenode #Cakey. Be warned though that this is not exactly a channel for programming beginners (ie, we may help with the basics, but we work on the advanced stuff more) ;).

**Comment by deadair3210** [comment]
GodMode9 launches correctly on both CakeHax and Gateway now! Congrats!

**Comment by d0k3** [comment]
Alright, thank you, for your patience, too! Closing this for now. If any similar problems should occur in the future, with any of my tools, just let me know.
