### ISSUE TITLE
Does not detect RedNAND

### ISSUE THREAD

**Issue by ronaldpabilonia** [d0k3/Decrypt9WIP#39]
Hello. I've a SysNAND 9.2 and a RedNAND 10.7. I am following Plailect's guide. I'm currently trying to get the OTP, and I need to dump the Health & Safety using Decrypt9. It gives me an error that says my SD is not formatted for EmuNAND. [Reference image](http://imgur.com/NYOk6hq). I am using the 20160404 version.

**Comment by d0k3** [comment]
I need more info... what is the console type of this, what did you use to create the EmuNAND? Also, use the System Info feature (in maintenance), to find your NAND size. And, what would help me a lot with this, is if you could dump and provide the MBR (that's the first 512 byte) of your SD card. HxD cann access physical drives like this.

**Comment by dark-samus** [comment]
redNAND working fine over here on the latest release, most likely it's a problem with how you set your redNAND up

**Comment by ronaldpabilonia** [comment]
Im using a NN3DSXL US, created EmuNAND using EmuNAND9. NAND size is 1,979,711,488 bytes. I don't know how to dump the MBR. Also I've set up RedNAND thrice already. I've reformatted twice but to no avail.

**Comment by ronaldpabilonia** [comment]
Nevermind guys. Just missing a couple of files (arm9, arm11) in the root of  the SD. Silly of me. Sorry for opening this issue. Thanks anyways!

**Comment by d0k3** [comment]
It is still strange, some missing files would lead to your EmuNAND not being detected. It does work now, and the error was on your side, right?
