### ISSUE TITLE
Failure to decrypt a .cia file?

### ISSUE THREAD

**Issue by NinjaBoyLao** [d0k3/Decrypt9WIP#41]
Why is this happening? it takes just as long to reach the "failed!" error message as it does to do a good decryption. Seems to happen randomly, it's happening now on .cia files i know for a fact ive decrypted before.

**Comment by d0k3** [comment]
Well, this information does not help much!

You need to provide the exact log (Decrypt9.log) and one CIA file that fails (**don't share any CIA files here**). What do you mean by randomly? If one CIA file fails to decrypt, you put the encrypted one back on the SD card, will it not fail again (hint: I'm sure it will fail again)? Also take note that the **verification'' will fail if you edit stuff in your CIA files.

**Comment by NinjaBoyLao** [comment]
Ah, my apologies. It was .cia file I had decrypted, then accidentally deleted the decrypted one before doing anything else. I then copied it back over to decrypt again, and it failed. I'm sure I no longer have the .log for when this happened, you may close this issue if you wish, and i will for sure let you know if it happens again.

**Comment by d0k3** [comment]
Alright, closing this now. If anything comes up, feel free to reopen.
