### ISSUE TITLE
Does not Detect redNand (either)

### ISSUE THREAD

**Issue by XcSwisp** [d0k3/Decrypt9WIP#42]
Hi d0k3, thanks for your hard work.

Exact same problem as https://github.com/d0k3/Decrypt9WIP/issues/39 :

I've a SysNAND 9.2 and a RedNAND 10.7. I am following Plailect's guide. I'm currently trying to get the OTP, and I need to dump the Health & Safety using Decrypt9. It gives me an error that says my SD is not formatted for EmuNAND.

Using latest version as well.

Im using a NN3DSXL EU, created RedNAND using EmuNAND9. I do have the files that were missing to previous OP in the root of my SD card.

Here are the first 1024 bytes of my SD card attached.

[EMUNAND9SD (G).zip](https://github.com/d0k3/Decrypt9WIP/files/213674/EMUNAND9SD.G.zip)

Please let me know if you need any other info.

Thanks !

**Comment by d0k3** [comment]
That's not the first 1024 bytes of your physical SD, it may be the first 1024 byte of the logical partition though. Plus, I'd need it in binary format (this text format is pretty unreadable). Can you dump the first ~1024 byte via HxD? Make sure you select the physical drive.

**Comment by XcSwisp** [comment]
I am not sure if I'm doing this right ... Is this the right file ?


[EMUNAND9SD.zip](https://github.com/d0k3/Decrypt9WIP/files/213906/EMUNAND9SD.zip)

Thanks for your help !

**Comment by d0k3** [comment]
It is not. Get HxD from here: https://mh-nexus.de/en/hxd/
Start it as admin. Open your physical SD card in Extra -> Open Drive. Copy the first ~1024 byte to some external file, and send me that.

**Comment by XcSwisp** [comment]
[EMUNAND9SD.zip](https://github.com/d0k3/Decrypt9WIP/files/213922/EMUNAND9SD.zip)

I wasn't running as admin. Here you go.

**Comment by d0k3** [comment]
Okay, seeing this now. Your EmuNAND is in fact not correctly formatted, it is ~944MB big, while the minimum EmuNAND size for an N3DS would be ~1240MB. In fact it looks almost like you did the EmuNAND setup on a O3DS and not on this console.

Can you give me some details about how you did the EmuNAND setup (on which console if not the same, which entrypoint, which EmuNAND9 version, etc...)? You also need to setup that RedNAND fresh, from scratch.

And, there is one more thing that would help me - run the system info feature from D9WIP, it is in maintenance. I need none of the identifying data, I just want to know if that console is correctly identified as a N3DS.

**Comment by XcSwisp** [comment]
I don't get it, my redNand is working ...

I followed this guide for installing it :

https://github.com/Plailect/Guide/wiki/Part-3-(RedNAND)

Same console, EU 3DSXL, entry point browserhaxx.

I do not find the maintenance option in D9WIP version 2016/03/09.

**Comment by XcSwisp** [comment]
NEVERMIND I was using an old version ... Now my RedNAND is detected.

Thanks for the amazing work and thanks for your help !

**Comment by reelspacewheels** [comment]
Just for reference. I, too, experienced this issue on my o3ds. It turns out there's an older version of Decrypt9WIP in the HBL starter.zip. I found there was a second version of your software on another page in HBL. 

Thanks so much for your work!

**Comment by d0k3** [comment]
I'll look into updating D9WIP in the extended homebrew starter pack then. Closing this now, as that issue is solved!
