### ISSUE TITLE
Failing to start up with A9LH

### ISSUE THREAD

**Issue by tasorn** [d0k3/Decrypt9WIP#43]
I have an o3DS running A9LH (AuReiNand 4.2) with an updated SysNAND (10.7). When I try to run Decrypt9, it gets to "Initialization: success!" and then stalls. The screen prints out:

Counting 15 submenus and 111 features
Initializing, hold L+R to pause

Initializing SD card... success
0x03 KeyX & KeyY: automatically set up
0x25 KeyX: loaded, verified, set up
0x18 KeyX: already set up
0x1B KeyX: loaded, verified, set up
Finalizing Initialization...

Initialization: success!

Afterwards, that text just stays on the screen and nothing changes, and the only way to get out is by turning the 3ds off.

**Comment by d0k3** [comment]
Can you try this with EmuNAND9 & GodMode9 and tell me if there are similar issues?

**Comment by tasorn** [comment]
EmuNAND9 and GodMode9 both run. 

I tried using a new SD card and now Decrypt9 is working, so I guess it was a problem with my SD card. Still strange that Decrypt9 was the only thing that didn't work.

**Comment by d0k3** [comment]
SD card failures can have strange effects, and the 3DS internal SD card reader is not the best. I personally have a suspicion even Nintendo implements software workarounds to make this crappy thing work properly.

Anyways, closing this now.
