### ISSUE TITLE
Launcher.dat entrypoint crashes when accessing ITCM

### ISSUE THREAD

**Issue by d0k3** [d0k3/Decrypt9WIP#45]
If launched via the GW Launcher.dat entrypoint and when accessing ITCM (f.e. for system info), Decrypt9WIP crashes. This has to be solved in gw-start.s:
https://github.com/d0k3/Decrypt9WIP/blob/master/source/abstraction/gw-start.s#L40-L46

**Comment by dark-samus** [comment]
@d0k3 this is most likely an issue with the MPU, most likely it is improperly set up (see here: https://github.com/d0k3/Decrypt9WIP/blob/master/source/abstraction/bs-start.s#L15-L37 ) I think the easiest way to fix this would simply be removing this: https://github.com/d0k3/Decrypt9WIP/blob/master/source/abstraction/gw-start.s#L43-L45

since the MPU is the Memory Protection Unit, and by default, I think, ITCM is protected it makes sense you're having trouble reading from it with the MPU enabled ;) anyways, hope you get it fixed :)

**Comment by gemarcano** [comment]
I don't think the answer is disabling cache. Based on 3dbrew, ITCM should have been configured to be in a RO region of memory by the 3DS software. Only other suggestions would be to flush cache (perhaps clean it also?), then letting it run. For a real good stretch, adding an interrupt handler to catch memory aborts could be a way to identify if something weird memory access wise is happening.

**Comment by d0k3** [comment]
There is nothing wrong with the MPU setup for the bootstrap binary (bs-start.s, which is used by Brahma & A9LH), everything works there. The two problems with editing gw-start.s for me are (1) I can't test this entrypoint myself, and (2) CakeHax will also be affected by gw-start.s.

It is confirmed, though, that this problem only happens with accesses to ITCM. You can confirm this yourself by using the system info feature in D9 (will crash from GW entrypoint) or trying to dump ITCM with GodMode9 (will crash, too).

**Comment by dark-samus** [comment]
@d0k3 my point was, you didn't carry over any of the ACTUAL MPU settings from bs-start.s, just the cache enables, itcm enable and MPU enable, which might cause problems since FIRMs MPU settings are still in place :)

**Comment by d0k3** [comment]
Okay, should be fixed now, in https://github.com/d0k3/Decrypt9WIP/commit/ca977ef22a636338c895d68faab9ae8fe6952b0b. Can anyone help me test this?

**Comment by d0k3** [comment]
Didn't mean to close, so anyone with an O3DS and compilation skills available?

**Comment by mariogamer2** [comment]
yes

**Comment by mariogamer2** [comment]
My sysNAND web browser is glitchy,it's always freeze on most pages...

**Comment by idgrepthat** [comment]
9.2 old3ds. works.

Interestingly, when I built the project with "make" first, then "make gateway" the launcher.dat was defective. when I built with "make gateway" straight from a cleaned repo, the launcher was good.

**Comment by idgrepthat** [comment]
One bug though, when running sys info on this build, it freezes right after the NAND CID line is printed.

**Comment by d0k3** [comment]
That's because TWL Customer ID needs access to ITCM, which the GW Launcher.dat entrypoint does not provide reliably. There are other problems with the Launcher.dat entrypoint, and I don't want this to hinder development, so the Gateway Launcher.dat entrypoint is now considered deprecated, see https://github.com/d0k3/Decrypt9WIP/commit/9f376bd2225569e01e2e186af5bcab0b31f1dec2

Closing this issue for now, Launcher.dat bugs will no more be fixed.

**Comment by mariogamer2** [comment]
@d0k3 What is exactly the LauncherTemplate.dat and what is the difference with CakeHax?

**Comment by d0k3** [comment]
This is the wrong place to ask questions such as this. LauncherTemplate.dat uses the GW closed source entrypoint (same es GW software). CakeHax is an open source entrypoint by mid-kid.

**Comment by idgrepthat** [comment]
@mariogamer2 this is for D9 issues not CFW#101
