### ISSUE TITLE
Bypass key combination for injecting

### ISSUE THREAD

**Issue by ndrs92** [d0k3/Decrypt9WIP#46]
Hi,

My 3DS has the select button always pressed, so I cant make the key combination to inject an app into H&S app.

Any chances to compile an uber-unsecure version for these cases? I know its a hassle.

Thanks in advance

**Comment by d0k3** [comment]
Well, that's an issue very specific for you. Change this...
https://github.com/d0k3/Decrypt9WIP/blob/master/source/menu.c#L127
to:
if (false) {

Then recompile. If you can't compile, ask someone to help you. Closing this now

**Comment by ndrs92** [comment]
Thanks man! It worked.

Frankly, I thought setting up the environment to compile this would be an enormous problem. Turns out... not, I had only to update glibc and the makefile did the rest.

Already injected FBI in the H&S app.

Thanks again!

**Comment by d0k3** [comment]
Good to hear! :+1:

**Comment by sebariosgrob** [comment]
Have the same issue, could you please share your modded Decrypt9? I have a broken "down" button.

Thanks in advance!

**Comment by ndrs92** [comment]
I had it wandering around in some folder in my server, so here it is. 
[modded-version.zip](https://github.com/d0k3/Decrypt9WIP/files/448221/modded-version.zip)
Remember is a version compiled in 23 Apr of 2016, so a little outdated probably.

**Comment by sebariosgrob** [comment]
sorry for the noob question, but it's not on .3dsx so won't show up on homebrew launcher, what am I missing?

thanks for the file by the way!

**Comment by ndrs92** [comment]
I don't remember how I launched but you need a launcher that suports .bin payloads like BootCtr
