### ISSUE TITLE
Add ability to dump NAND in any file

### ISSUE THREAD

**Issue by mariogamer2** [d0k3/Decrypt9WIP#47]
What I mean is that when dumping,it will ask for a name to the user with a "virtual keyboard" where user tap the name

**Comment by d0k3** [comment]
While I see how this can be useful, this would be too much work for such a side feature and there are no examples of handling the touch screen on ARM9 yet (meaning: no guarantees that it works reliably enough at all).

The current choice of output file names should already be enough to differentiate the files themselves, and you can rename them in other tools.

Closing this for now.
