### ISSUE TITLE
Number of installed emuNANDs is greater than the actual number of installed emuNANDs

### ISSUE THREAD

**Issue by fox8091** [d0k3/Decrypt9WIP#50]
If you open System Info, it shows the number of installed emuNANDs as 5 on my console, however, I only have 2. If I look one line down at the list of installed emuNANDs, I have 2, emuNAND #0, a GW emuNAND, and emuNAND #1, a redNAND.

**Comment by d0k3** [comment]
Looking at it now, wtf did I think? I guess I was tired when coding this. Thanks for pointing this out!
