### ISSUE TITLE
Generating a seeddb with no seeds generates a 0 byte file

### ISSUE THREAD

**Issue by fox8091** [d0k3/Decrypt9WIP#53]
This wouldn't be considered an issue on it's own, but the "update seeddb" option checks if it's a 0 byte file and errors due to a "file too small" error.

**Comment by d0k3** [comment]
This needs to be checked - D9 does not create the seeddb.bin as a zero byte file, it instead writes a 16 byte one, which should cause no issues. Can you doublecheck this? Reproduce it, maybe, or check if the file is really zero byte?

**Comment by fox8091** [comment]
Cannot reproduce.
