### ISSUE TITLE
Inject files options for emuNAND isn't updated

### ISSUE THREAD

**Issue by Yoshistar95** [d0k3/Decrypt9WIP#54]
It seems "Inject files..." for emuNAND isn't properly updated since it still has the seed option (keep forgetting the name lol) and it lacks the option to inject friendsaves.bin to emuNAND, I used both .3dsx and .dat version to make sure it isn't specifically the built I used.
Dump list is fine, so kinda weird the inject list is slightly off haha

**Comment by d0k3** [comment]
Good catch, thank you!
