### ISSUE TITLE
Dec9 (latest and 20160412,0428) Hangs up on a Old3DS

### ISSUE THREAD

**Issue by Kikoshi** [d0k3/Decrypt9WIP#56]
Hello, 
After the initial setup/read it ends with Success.. but it doesn't do anything after that, its stuck*frozen* there.
Emu9 does boot up without issues, but not Dec9 :/. 
I just updated my console to O3DS 11.0 (a9lh) US
-- Gave your Nightly a test run 2016/05/17 version and still nothing :(.

**Comment by d0k3** [comment]
Okay. Is this a 128GB card and what did you use to format it? If the answer is Easeus Partition Manager, you won't be able to get it working, otherwise the formatting is still most likely the problem.

EmuNAND9 (even without seting up an EmuNAND) is the recommended way of formatting any SD card.

**Comment by urherenow** [comment]
What are you talking about? I've used a 256GB card formatted /w Easeus and it worked for CFW and stuff. What's the difference with dc9?

**Comment by urherenow** [comment]
Then again, the OP says Emunand9 works on the card... So I'm still confused.

**Comment by d0k3** [comment]
There are a lot of people for whom Easeus formatted cards do not work. It may be a combination of console, card and formatting, I'm unsure yet. EmuNAND9 works without an SD card, or with a totally corrupted one, too, (Decrypt9 does not) so that may be that.

**Comment by Kikoshi** [comment]
Alright, I'll give it a shot and format it with emunand9

**Comment by d0k3** [comment]
Well, I see Easeus recommended a lot of times, when it actually is not a good software for this. It may work in many cases, but it does not in all.

My recommendation for formatting any 3DS SD card is EmuNAND9, but the official formatter is fine, too.
