### ISSUE TITLE
Ability to create cias on the 3ds directly from a 3ds file

### ISSUE THREAD

**Issue by poutros** [d0k3/Decrypt9WIP#58]
You can already create the xorpads. I don't see why there is a need for a pc program to do the cia building job when you can already decrypt and encrypt a 3ds/cia file on the 3ds itself.

**Comment by d0k3** [comment]
You seem to think that generating XORpads is the most complicated thing when creating CIAs from .3DS files, but in fact it is just the one that requires hardware. In the actual conversion process, you are also using makerom, which is pretty complicated software, and it does it's job well. I can't do makeroms job as good as makerom does it, so this will not be added to D9. Closing this issue now.

What CIAngel does (if that should come up) is also different, cause the CDN download actually contains everything required for a CIA, while a .3DS does not.

**Comment by poutros** [comment]
Oh, didn't know about that. Ok then.
