### ISSUE TITLE
FIRM ARM9 Decryptor failing

### ISSUE THREAD

**Issue by NinjaBoyLao** [d0k3/Decrypt9WIP#59]
Is this normal for having a9lh installed? i just dumped the firms, basically just testing out the new features you implemented. i like to feel useful

**Comment by d0k3** [comment]
With A9LH installed, FIRM0 is partially corrupted (FIRM1 is not). That's the reason why the ARM9 decryptor does not work for FIRM0. So, yup, it is perfectly normal.

You can also try out the ARM9 decryptor with the new NCCH FIRM dumper, btw. That feature dumps NATIVE_FIRM, SAFE_MODE_FIRM, TWL_FIRM, AGB_FIRM and also decrypts them.

Closing this now, feel free to reopen if you think there is still an issue.

**Comment by NinjaBoyLao** [comment]
oh, uh, i did that. i dumped the NCCH FIRM's, and then tried decrypting all 4 of them. all four failed, and im not sure why. i provided a clean copy of secret_sector.bin, i have no idea what slot0x11Key95 would look like even though i have slot0x11Key96. I'll run through it again to make sure i have a .log and then i'll post it here

**Comment by NinjaBoyLao** [comment]
[Decrypt9.zip](https://github.com/d0k3/Decrypt9WIP/files/303824/Decrypt9.zip)
here you go. just realized it might be saying "failed" just because its already decrypted. might wanna change that to where it doesnt fuss at the user if the selected action has already taken place, for instance, what you made it say when attempting to decrypt an already-decrypted .cia

**Comment by d0k3** [comment]
These are O3DS FIRMS, they don't have the arm9 binary encryption, thus I can not decrypt it. It says: Section 2 does not look encrypted (which is right, it is not encrypted). The action in that case is failed in the sense that we asked it to decrypt a N3DS FIRM, and it could do nothing. I'd rather solve this with some preselection (not even enabling users to select unencrypted ones). I'll look into it.

Also, keys. You have that secret_sector.bin file. slot0x11key95.bin is bytes 0...16 of it. slot0x11key96.bin is bytes 16...32 of it.

**Comment by NinjaBoyLao** [comment]
ah, thank you. apologies for my stupidity, im still earning how things work as i go along.
