### ISSUE TITLE
Fix BrahmaLoader

### ISSUE THREAD

**Issue by fox8091** [d0k3/Decrypt9WIP#61]
BrahmaLoader needs updated to use the latest libkhax, otherwise you get compile errors with the latest ctrulib.

**Comment by fox8091** [comment]
Another thing, you have to remove the aptOpenSession and aptCloseSession calls in main.c of BrahmaLoader and apply the same isNew3DS fixes applied in libkhax to brahma.c

**Comment by d0k3** [comment]
Fixed. You should have made that a BrahmaLoader issue.

**Comment by fox8091** [comment]
BrahmaLoader doesn't have issues open..

**Comment by d0k3** [comment]
Alright, I added issues to the repo. If you can, could you give the Brahma entrypoint a try and tell me if it works for you?
