### ISSUE TITLE
Can not found "Gamecart Dumper Options"

### ISSUE THREAD

**Issue by chinanoahli** [d0k3/Decrypt9WIP#62]
I am using Decrypt9WIP all-in-one 20160626 version of Decrypt9WIP.
I want to dump my gamecart, but I can not found the Gamecart Dumper Options?
I tried inserted the gamecard before enter Decrypt9WIP and inserted the gamecard after enter Decrypt9WIP, but Gamecart Dumper Options did not show once.
How can I make it work?
Thank you.

**Comment by d0k3** [comment]
I suggest you download again and make sure you're running the correct payload. Also, pls close this issue if the problem was on your side.

**Comment by chinanoahli** [comment]
It looks like I install D9W in a wrong way, now I can dump my card, thank you and sorry to bother you.
