### ISSUE TITLE
[Suggestion] Colored text when option is selected.

### ISSUE THREAD

**Issue by 3xkrazy** [d0k3/Decrypt9WIP#63]
I noticed that you added colored output text when a task succeeds. GodMode9 looks really nice aesthetically, so I was wondering why Decrypt9WIP didn't get the same treatment. Also, could you consider adding colored text when an option is highlighted?

**Comment by d0k3** [comment]
I'll think about it. Color could also be used to highlight the potential danger of a feature (for none/EmuNAND/SysNAND/A9LH). Leaving this open for now.

**Comment by d0k3** [comment]
Color (only subtle changes) introduced with https://github.com/d0k3/Decrypt9WIP/commit/a5440c0a6f0dd1a145a6f9f837b9ce350037710b
