### ISSUE TITLE
Add nds cart dumping

### ISSUE THREAD

**Issue by poutros** [d0k3/Decrypt9WIP#65]
Some work has already been done in [this](https://github.com/GerbilSoft/uncart-ds/tree/implement-ntr-twl-dumping) repo but it seems like it has stalled.

**Comment by d0k3** [comment]
NDS cart dumping is not trivial stuff. Once it is figured out, it will be added to D9. I'm leaving this open because this is, in fact, a planned feature. Don't expect anything to happen soon, though.

**Comment by PokeAcer549** [comment]
IIRC uncart had some sort of dump code :p

**Comment by d0k3** [comment]
D9 has exactly the same dumping code as uncart... and no, DS cart dumping does not work yet

**Comment by osilloscorpion** [comment]
support nds cart dumping.(However, there is a need to look for [key1.h] from wooddumper)
https://github.com/osilloscorpion/Decrypt9WIP/commit/37130fd1abb2266e091f8bfe89e38a4ed563ad01

**Comment by osilloscorpion** [comment]
support nds cart dumping.(However, there is a need to look for [key1.h] from wooddumper)

https://github.com/osilloscorpion/Decrypt9WIP/tree/dump_nds_cart

**Comment by osilloscorpion** [comment]
support nds cart dumping.

https://github.com/osilloscorpion/Decrypt9WIP/tree/dump_nds_cart

**Comment by osilloscorpion** [comment]
support nds cart dumping.
Please merge the source code
https://github.com/osilloscorpion/Decrypt9WIP/tree/dump_nds_cart

**Comment by ihaveamac** [comment]
so far it was able to dump my Animal Crossing: Wild World game card, as well as Warioware: DIY. it doesn't dump Pokémon Black (DSi-enhanced) though.
```
Selected: [Dump Cart (full)]
Cartridge ID: C001FFC2
Product name: POKEMON B
Product ID: IRBO01
Cartridge data size: 256MB
Cartridge used size: 195MB
Cartridge dump size: 256MB
Invalid SecureCartID. (D0EE2866 != C001FFC2)
Error reading secure data
Dump Cart (full): failed!

Press B to return, START to reboot.
```

**Comment by osilloscorpion** [comment]
DSi(Hybrid or enhanced) is not supported, because the protocol is different.

**Comment by idgrepthat** [comment]
It dumped Biggest Loser US just fine. It dumped a DS mode copy of course and it ran fine on desmume.
On DSi mode from no$gba, it crashed as expected.

![capture](https://cloud.githubusercontent.com/assets/11487157/17456553/ff990ef6-5ba0-11e6-9c8f-1355fff545c2.PNG)


btw -  any reason why it's so slow compared to DSi version?

**Comment by ihaveamac** [comment]
I was told Pokémon HeartGold [failed as well](https://cdn.discordapp.com/attachments/196635745551646720/211457693318119425/e5d3cdf7-7568-441a-8b2c-11fdd751f0f61053773678.jpg), with a similar issue to Black. both of these games have extra hardware in the game card (infrared), so could that be it?

**Comment by idgrepthat** [comment]
System Flaw also dumped. Looks like just the crypto is wrong (on second look, all the header past 200h is missing). It will boot the ingame "wrong system" error screen at least.

**Comment by osilloscorpion** [comment]
Add error : DSi(Hybrid or enhanced) is not supported
https://github.com/osilloscorpion/Decrypt9WIP/tree/dump_nds_cart

**Comment by idgrepthat** [comment]
>Add error : DSi(Hybrid or enhanced) is not supported
>https://github.com/osilloscorpion/Decrypt9WIP/tree/dump_nds_cart
I think a warning would be more appropriate since this appears to still dump usable hybrid carts in DS mode. Check up a few posts with Biggest Loser.

**Comment by ihaveamac** [comment]
it also apparently failed with Pokémon Platinum, which as far as I know has no special hardware or anything.
```
Selected: [Dump Cart (full)]
Cartridge ID: 80007FC2
Product name: POKEMON PL
Product ID: CPUE01
Cartridge data size: 128MB
Cartridge used size: 99MB
Cartridge dump size: 128MB
Invalid SecureCartID. (D0EE2866 != 80007FC2)
Error reading secure data
Dump Cart (full): failed!

Press B to return, START to reboot.
```

**Comment by d0k3** [comment]
Okay, first of all, thanks for that pull request. This is a  big step forward! As there is still some testing going on and there are still commits coming, I'll wait for a bit, right?

Once I take it over, I may also do some squashing and I may change a thing or two (f.e. we need to prevent users trying to make CIAs from NDS carts, and I am atm unsure if trimming works when dumping DS carts.

**Comment by ihaveamac** [comment]
small note @d0k3 trimming did work properly for me (.nds was trimmed when I picked "trim")

**Comment by osilloscorpion** [comment]
Please (long?)wait because it is still necessary to test.

**Comment by d0k3** [comment]
Alright, I'll wait.

**Comment by osilloscorpion** [comment]
When contains 80000000 in cartID, it has special operation.
try to adjust the readTimeout(Delay) of NTR_CmdSecure

**Comment by osilloscorpion** [comment]
For example,
secure_ntr.c: 210
u16 readTimeout = *((u16*)&header[0x6E]);
readTimeout + = 3000;

**Comment by osilloscorpion** [comment]
hi, **ihaveamac**
please test Pokémon Platinum
SecureCartID Ok?
https://github.com/osilloscorpion/uncart-ds/tree/implement-ntr-twl-dumping

**Comment by ihaveamac** [comment]
@osilloscorpion can't seem to run that through a9lh.... using v2 and luma chainloader

**Comment by osilloscorpion** [comment]
I'm using in A9LH and Luma. It worked properly.

**Comment by idgrepthat** [comment]
I think you have to use make a9lh for it to work. Anyway, here's a d9wip that dumps platinum just fine for me.
[decrypt9WIP.zip](https://github.com/d0k3/Decrypt9WIP/files/405595/decrypt9WIP.zip)

**Comment by PokeAcer549** [comment]
Platinum is a very regular game; that's quite odd x3

**Comment by LiquidFenrir** [comment]
I tried dumping Spectrobes (NTR-ASUP-EUR) and Final Fantasy IV (NTR-YF4P-EUR), spectrobes worked but FF didn't. Relevant part of log: http://pastebin.com/S15AZKAp

**Comment by PPLToast** [comment]
A9LH is required for NDS dumping? Might explain why it's all crashing for me...

**Comment by idgrepthat** [comment]
>A9LH is required for NDS dumping? Might explain why it's all crashing for me...

Here's a full release build
[Decrypt9WIP-20160807-171527.zip](https://github.com/d0k3/Decrypt9WIP/files/405781/Decrypt9WIP-20160807-171527.zip)

**Comment by osilloscorpion** [comment]
@LiquidFenrir 
when you use the uncart-ds, SecureCartID is displayed correctly?
https://github.com/osilloscorpion/uncart-ds/tree/implement-ntr-twl-dumping

**Comment by d0k3** [comment]
@osilloscorpion once this is ready for take over into my branch, just let me know. You can also do a pull request if you want.

**Comment by LiquidFenrir** [comment]
@osilloscorpion I'm not sure what you mean by "displayed correctly", using that thing showed "Secure chip ID: D0EE2866", and "Chip ID is 80007FC2" for FFIV

**Comment by PPLToast** [comment]
@idgrepthat This worked for me with 3dsx, dumped a few games along with Platinum and all worked fine (except TWL of course) good stuff :)

(oh and platinum did result in a "bad" dump for whatever reason, CRC32 2ADABB54 rather than 71ACA63A, idk why)

**Comment by osilloscorpion** [comment]
Please merge the source code
https://github.com/osilloscorpion/Decrypt9WIP/tree/dump_nds_cart

**Comment by poutros** [comment]
@osilloscorpion Make a pull request.

**Comment by osilloscorpion** [comment]
I will go away
It was between short but thank you everyone.

**Comment by idgrepthat** [comment]
Wow he committed suicide XD

**Comment by idgrepthat** [comment]
Well here's my local changes since he's gone. Do with it what you will.
- increased compatibility with increased read delay (that he suggested above)
- fixed file write buffering for about a 20x speedup.
[Decrypt9WIP.zip](https://github.com/d0k3/Decrypt9WIP/files/406651/Decrypt9WIP.zip)

**Comment by d0k3** [comment]
@idgrepthat can you do a pull request with that? @osilloscorpion's account seems to be gone, so we can't credit him anymore (which I would want)

**Comment by idgrepthat** [comment]
Yah, just give me a bit.

**Comment by PokeAcer549** [comment]
Pokemon W works fine with dumping, and the warning shows up perfectly clear so yay :D

**Comment by d0k3** [comment]
Added with https://github.com/d0k3/Decrypt9WIP/commit/34e96d0e9dca28b746d2ac577f27d112fe19c4e3

Thanks osilloscorpion, @idgrepthat, all testers and everyone involved!
