### ISSUE TITLE
Injecting/dumping H&S app via A9LH also keeping A9LH while forcing

### ISSUE THREAD

**Issue by v0idst4r** [d0k3/Decrypt9WIP#66]
Can someone explain why it's not possible? I kind of screwed myself. I have a emunand and sysnand both with 11.0 but a 9.1 nand backup that cant be restored because it thinks its from another 3DS. Also how can I force the nand backup while keepong A9LH installed? I don't feel like going through a9lh again ;-;

**Comment by v0idst4r** [comment]
I think I might have it. I forced the backup to emu then I'll back up emu and restore it to sys with keep a9lh

**Comment by d0k3** [comment]
That backup is most likely broken, if it does not, in fact, come from another 3DS. The safety checks in D9 are pretty accurate, and I don't know of a single instance where they want wrong. Meaning (for you): Force inject this to SysNAND, have a brick. In any case, try if that EmuNAND works before doing anything stupid.

Also, help us find out what's wrong here by providing the relevant text from the log file.

**Comment by v0idst4r** [comment]
Well I formatted my sysnand

**Comment by v0idst4r** [comment]
Might that be why?

**Comment by d0k3** [comment]
No. Provide the log. Also, this issue has nothing to do with H&S inject / dump, so better reword it.

**Comment by v0idst4r** [comment]
Ah I know it doesn't I thought it'd be more efficient to make 1 issue.

**Comment by v0idst4r** [comment]
I'll send the log after I check if it works on emi

**Comment by v0idst4r** [comment]
It works on emunand. Not sure why it said it wasnt for this 3ds when I in fact made the backup on it... I'll send logs in a bit after I unfuk everything else

**Comment by v0idst4r** [comment]
https://ghostbin.com/paste/7wkyr/raw

**Comment by v0idst4r** [comment]
For some reason I couldn't do h&s dumping until I added slot0x25 to my sd card... Does it think my N3DS is a O3DS?

**Comment by urherenow** [comment]
Not sure why it seems it can't get the slot 0x25 key, except for once, but maybe you'll have more luck placing the .bin s on your SD root. 0x25 and 0x1B.

Unless the real problem is that you ARE using .bin files for the keys, and they're wrong...

**Comment by v0idst4r** [comment]
I placed 0x25 and it dumped I have yet to see if it works when I inject FBI

**Comment by d0k3** [comment]
Okay. First of all, requiring the slot0x25keyX file is not an issue. This one may not be available on a9lh, so you need to get it. Also, your log - I don't see any failed NAND restores in there, in fact the (keep A9LH NAND restore worked fine)... so, what's the issue? :)

**Comment by v0idst4r** [comment]
That's the log after I forced to emunand, backed up emunand then restored
emu to sys with keep a9lh.

**Comment by d0k3** [comment]
Normally that should not have worked... Did you by any chance mess up the .sha file? Anyways, I would have wanted to know, but seeing there is no issue anymore, this can be closed, right?

**Comment by v0idst4r** [comment]
Well when I did A9LH I used a different SD card and that's the one I made
the backup on. I might not have copied the sha...

**Comment by d0k3** [comment]
You actually messed up the .sha, most likely, cause without one it would have worked. Closing this now...
