### ISSUE TITLE
NCSD "writer/dumper"

### ISSUE THREAD

**Issue by mariogamer2** [d0k3/Decrypt9WIP#68]
I mean ,by NCSD writter, the "Unbrick FW 2.1 EmuNAND" option in OTPHelper

So,you probably know that there is a dev update for old 3ds USA.
For other region,it is simple,we just need to follow the Region Change Guide....

But for New 3DS,I was thinking that this MAY work:

 1. Change region (if you are in EUR/JPN)
 2. Create an EmuNAND 3.Follow the downgrade to dev FW process
 3. Your EmuNAND will be bricked,then we can rewrote NCSD,and other
 4. Restore EmuNAND to SysNAND

Does it is possible? If yes,can you reimplement this on OTPHelper or D9WIP?

**Comment by d0k3** [comment]
This does not belong in here - this is Decrypt9, not OTPHelper. Also, the process is a little more complicated, and people are already working on it. It will still take some time, tough. It may get included in OTPHelper later, if there is enough interest in it.

**Comment by mariogamer2** [comment]
Ok thank.

Do you know these people?
