### ISSUE TITLE
H&S Injection in iQue / Taiwan 3DS consoles

### ISSUE THREAD

**Issue by d0k3** [d0k3/Decrypt9WIP#70]
As referenced by this pull request:
https://github.com/d0k3/Decrypt9WIP/pull/67

This needs a cleaner solution.

**Comment by d0k3** [comment]
@soarqin
Maybe we can discuss this on here?

I just tried download all possible KOR/TWN/CHN versions of H&S via 3DNUS. Guess what, each and every one of them had a proper size. So the issue at hand has to do with (certain?) factory fresh consoles maybe.

Your inital solution involved just checking all regions, and discarding those that have a < 64kB app0, right? And the actual H&S app that matches the region of the console is just a stub, right?

**Comment by soarqin** [comment]
yes, but I cannot find anyone with KOR console to cinfirm that, only CHN/TWN consoles(but heard many) are confirmed. Also as you said, the tiny h&s app which is not in console region is not found in nus updates. It mostly like they are installed in factory initial state.

**Comment by d0k3** [comment]
So what title id does the tiny stub have? And what title id does the actual H&S app have?

**Comment by soarqin** [comment]
0004001000026300 for TWN and 0004001000028300 for CHN as a tiny 15KB app

**Comment by d0k3** [comment]
Okay... and the actual, correct one is 0004001000027300 for both?

**Comment by soarqin** [comment]
correct one is the titletid in their own region, 0004001000026300 for CHN and 0004001000028300 for TWN

**Comment by d0k3** [comment]
Okay, I had an idea - we just change this code so that it only checks in the correct region - that will work, right?

**Comment by soarqin** [comment]
agree, we do not need to support  region mismatching h&s apps in nands

**Comment by d0k3** [comment]
Okay, can you test this build and tell me if it fixes that problem?
https://transfer.sh/5kfRF/decrypt9wip-20160810-183728.zip

**Comment by d0k3** [comment]
@soarqin: Any update on this? As the H&S dumper / injector now selects the title to dump / inject on the region (from SecureInfo_A), that issue should be resolved. The new code works (on E/U/J units) and is tested, too.

**Comment by soarqin** [comment]
@d0k3 sorry for late to response. I tried it on my TWN console and it worked fine, but not yet tested on any CHN unit due to lack of testers.

**Comment by d0k3** [comment]
Alright, then I'll just assume CHN is also fixed. Feel free to reopen if anything comes up
