### ISSUE TITLE
problem with gba vc save injection

### ISSUE THREAD

**Issue by fikatr** [d0k3/Decrypt9WIP#73]
hey m8 whenever when i try to dump gba vc save its always telling me
GBA VC save dump : failed
slot0x24key y not set up

**Comment by obscurename** [comment]
Google "Keyname Pastebin".

**Comment by fikatr** [comment]
i cant find anything about it

**Comment by mariogamer2** [comment]
Do you have an account on GBAtemp or skype?

Also this is not really an issue,since it is specified in README.

**Comment by fikatr** [comment]
im sorry i didnt know what to do i already fixed it someone can close issue

**Comment by d0k3** [comment]
No problem, closing this
