### ISSUE TITLE
Official DS and DSi developer cards fail to dump.

### ISSUE THREAD

**Issue by Poryhack** [d0k3/Decrypt9WIP#75]
I'm using the latest pre-compiled release. I'm aware that DSi is not supported without a newer build from the dev branch. While it's not strictly related, I'd like to point out that issue #74 is marked closed but has apparently not been 100% fixed yet. Moving on to the nitty gritty...

NTR dev cart output:
```
Selected: Dump NTR Cart (full)
Cartridge ID: 0000FFC2
Cartridge Type: NTR
Product name:
Product ID:
Cartridge data size: 0MB
Cartridge used size: 4095MB
Cartridge dump size: 0MB
DSi Cartridge is not supported
Dump NTR Cart (full): failed!
```

TWL dev cart output:
```
Selected: Dump NTR Cart (full)
Cartridge ID: C000FFC2
Cartridge Type: NTR
Product name:
Product ID:
Cartridge data size: 0MB
Cartridge used size: 4095MB
Cartridge dump size: 0MB
DSi Cartridge is not supported
Dump NTR Cart (full): failed!
```

For what it's worth, dumping CTR dev cards does appear to work, but will not allow you to dump a blank cart. Being able to dump blanks (raw) would be a nice feature, but I suppose I should submit that in a separate request.

I know not everyone has access to the requisite hardware to test this, so please let me know if there is any experimentation/etc I can assist with. Thanks contributors! Decrypt9 is great; here's hoping we can make it a little better!

**Comment by Normmatt** [comment]
Are both of those carts blank? I haven't looked too much into dev ds carts as they seemed to always work... dev TWL carts might use a different key...

**Comment by Poryhack** [comment]
Apologies all, as Normmatt guessed the NTR and TWL flashcards I was attempting to dump were blank; I had foolishly assumed they had content on them when I posted this issue. I would still like to be able to dump "blanks" to search for previously written ROMs but I will re-post that as a separate issue where it belongs.
