### ISSUE TITLE
Decrypt9 loads to a black screen when launching from Homebrew Launcher

### ISSUE THREAD

**Issue by inputfail** [d0k3/Decrypt9WIP#76]
I see the usual flash of black/red like when loading EmuNAND9 (which works), but then all I see is an empty black screen with the backlight on. Launching from sysNAND ver. 9.2 with menuhax (themehax) and Homebrew Launcher

**Comment by inputfail** [comment]
For reference, it worked perfectly when loading via Cakehax earlier today (when I was still on v4.4)

**Comment by inputfail** [comment]
I just downloaded the previous release (June 26), and that works. Please let me know if you need any more info from me. Thanks for providing this tool to us open source!

**Comment by breakingspell** [comment]
Same behavior on freshly downgraded and formatted 9.2 sysnand launched through Menuhax. No logs on the SD, but the previous version still works fine

**Comment by inputfail** [comment]
Mine was an o3DS XL as well if that matters

**Comment by idgrepthat** [comment]
something's wrong with his build environment but this dude's version works ok for me
https://gbatemp.net/attachments/decrypt9wip-20160811-181557-zip.58748/

**Comment by Margen67** [comment]
This happened with the O3DS I've been installing A9LH on, but an older version worked fine.

**Comment by d0k3** [comment]
Can you try the fixed 3DSX I just attached to the release post?
https://github.com/d0k3/Decrypt9WIP/releases/tag/20160810

**Comment by d0k3** [comment]
Okay, I actually found a way to fix this permanently. As I already had a succesful tester, I am closing this now. You guys please test the latest release (today's), too, and let me know if there are any problems.
