### ISSUE TITLE
[Issue/Question] Creating a transferable 2.1 CTRNAND on a New 3DS

### ISSUE THREAD

**Issue by dedChar** [d0k3/Decrypt9WIP#79]
This is probably more of me asking if this would be possible, than a real bug.   
So I wanted to try out the new transferable CTRNAND feature, so I could finally install a9lh on my broken New 3ds and my plan was as follows:

- [x] Succesfully uninstall a9lh on second non-broken n3ds
- [x] Downgrade to 2.1
- [ ] Create Transferable CTRNAND
- [ ] Transfer to broken n3ds
- [ ] Get OTP
- [ ] Install a9lh

Now my problem is that my plan doesn't work, because I can't create a transferable 2.1 CTRNAND on a New 3ds. Decrypt9 just gives me this: 
```
Selected: [Dump transferable CTRNAND]
Corrupt partition or decryption error
Dump transferable CTRNAND: failed!
```

So is it just Decrypt9 refusing to create the transferable 2.1 CTRNAND, or is it just plain impossible to create one on a New 3ds?

**Comment by d0k3** [comment]
You don't even need to uninstall A9LH on the second N3DS. However, you need a 2.1 transferable from an O3DS. Maybe you can get someone to provide it for you if you don't own a O3DS console?

**Comment by d0k3** [comment]
A suggestion: Come join us on IRC freenode #Cakey. If I'm not on, ask for Al3x_10m. What you intend to do is possible, and we will help with any questions you have.

**Comment by dedChar** [comment]
I guess I can close this now :) Thank you guys for helping out :)
