### ISSUE TITLE
how success % i have when use this tool to extract nitendo 3ds file?

### ISSUE THREAD

**Issue by jameshentai** [d0k3/Decrypt9WIP#80]
i mean after hack, is i will have a 3d model file, script file, animation file ( that is all game data in nitendo 3ds file )? you say decrypt9WIP use for hack 3ds file, right?

**Comment by khang06** [comment]
What

**Comment by mariogamer2** [comment]
There is no (for now) extraction tool in D9WIP.

**Comment by d0k3** [comment]
What you're searching for us ctrtool. Maybe take a look at my 3DS Tools repo on Github?
