### ISSUE TITLE
How to use Decrypt9WIP, please post a tutorial ?

### ISSUE THREAD

**Issue by jameshentai** [d0k3/Decrypt9WIP#81]
I have this file 3ds game: Kingdom Hearts 3D - Dream Drop Distance.3ds . How to extract it? How to use Decrypt9WIP?

**Comment by urherenow** [comment]
This isn't a forum.

**Comment by d0k3** [comment]
Oh well, you're that guy from the other issue -_-. Use Google, goddammit. This is not a forum
