### ISSUE TITLE
GBA EEPROM save support?

### ISSUE THREAD

**Issue by agufungus** [d0k3/Decrypt9WIP#82]
Hello, I've been using the new GBA save feature, and so far it works pretty well with SRAM and Flash saves, but not with EEPROM; instead, it gives me a blank save when I try to inject them for games like Super Mario Advance 3 (official release). Will support for EEPROM be added in the future, or is there something I need to modify to the save to make it work?

**Comment by dark-samus** [comment]
The support for eeprom saves isn't in the official AGB_FIRM, nothing we can
do about that.... There is a fix for it, you'll have to google and find that

**Comment by d0k3** [comment]
If you find that fix, can you add a link here, then close this issue?

**Comment by agufungus** [comment]
So far, the only application that can handle EEPROM saves is AGBsave9. Maybe a fix could be based on that application's method, or maybe something better.

**Comment by d0k3** [comment]
As @dark-samus said - this is nothing that can be handled in D9. Injected VC GBA rom never use EEPROM. Use a tool like [GBATA](http://www.no-intro.org/tools.htm) to convert the rom for your emulator to SRAM, then you can also use the svae dumped via D9.
