### ISSUE TITLE
DS mode will not boot following Plailect A9LH guide

### ISSUE THREAD

**Issue by TheAquaSheep** [d0k3/Decrypt9WIP#85]
Following from this issue ( https://github.com/Plailect/Guide/issues/412 ).

It appears that in some instances, seemingly with original firmware lower than 9.2.0, performing a ctrtransfer causes Nintendo DS Settings, in the Settings menu, to fail to load and produce a black screen.

There are also issues in playing DS games on the 3DS.

I believe there is an issue in the ctrtransfer as I have tested a completely OFW firmware on 7.1.0 to be working.
After performing ctrtransfer to version 9.2.0, again OFW, the DS mode settings and DS game ( Pokemon Black/White ) fail to load.

Another person noted issues transferring from version 6.X.X

**Comment by d0k3** [comment]
Closing this, solution is found in Plailects guide.
