### ISSUE TITLE
new3ds firm 11.0.33 Decrypt9WIP current version dont boot

### ISSUE THREAD

**Issue by master861** [d0k3/Decrypt9WIP#86]
If i download the new version release it dont work any more for me on version 11.0.33 an older realease works for me it is this realease number 2016/08/14
Arm9loaderhax is installed on version 2 and cfw is luma 6.1.1

**Comment by dark-samus** [comment]
How exactly are you booting D9? It isn't compatible with 11.0, unless you boot it using a9lh. So, booting from the homebrew launcher and it not working is expected

**Comment by master861** [comment]
no i boot it from a9lh like this luma/payloads y_Decrypt9WIP.bin
only this version number dont works for me
 orther repos from d0k3 works for me

**Comment by Margen67** [comment]
Have you tried using a shorter name like y_D9WIP?

**Comment by master861** [comment]
now it works with the short name why it now works with the short name ?

**Comment by Margen67** [comment]
There's a character limit.

**Comment by ihaveamac** [comment]
there hasn't been a character limit with luma for a while now, so it could be something else.

**Comment by dark-samus** [comment]
There still is a character limit, but it's imposed by the filesystem rather
than luma... Anyways, it's irrelevant in this case, since both names should
be below the limit

**Comment by master861** [comment]
Hourglass9 works with this for me start_Hourglass9.bin and that is are longer name then y_Decrypt9WIP.bin

**Comment by d0k3** [comment]
Not a Decrypt9 issue, obviously. Open an issue in the Luma3DS repo, but only after you made 100% sure the error is not on your side.
