### ISSUE TITLE
'Dump & Decrypt Cart' option is not properly updating the Card Info header.

### ISSUE THREAD

**Issue by Poryhack** [d0k3/Decrypt9WIP#87]
When using the 'Dump & Decrypt Cart' option, the flag in NCCH 0's header that indicates whether it is encrypted or not is (correctly) modified to indicate that it isn't encrypted. However, a copy of NCCH 0's header exists in the NCSD's 'Card Info' header at offset 0x200. The flag doesn't appear to be being updated as it should be in that copy. I assume this is a bug since the two header copies in legit NCSDs (.cci/.3ds files) seem to always match up; if it's not I'd be interested to hear the rationale. Thanks!

References:
https://www.3dbrew.org/wiki/NCSD#Card_Info_Header
https://www.3dbrew.org/wiki/NCCH#NCCH_Flags

**Comment by d0k3** [comment]
Well, tbh, I am unsure. The two headers do not match up, though. It excludes the RSA signature. Any other opinions? Also, is there any issue coming from this not being updated?

**Comment by Poryhack** [comment]
No issue that I'm aware of. I only noticed because I was doing a byte-by-byte comparison of a Decrypt9-produced decrypted dump and a 3dstool (https://github.com/dnasdw/3dstool) produced rebuild of the CCI. The only difference was the flag inside of the duplicated header.

I understand that legitimate dumps are never decrypted, but I think the closest thing to legitimate is to have the two copies of the NCCH header match 1:1. The RSA signature is not included by design so that shouldn't be an issue.

**Comment by d0k3** [comment]
Alright, agreed. Fixed in https://github.com/d0k3/Decrypt9WIP/commit/b589127f36ebc00441845144e2e87c9ab9660d43
