### ISSUE TITLE
[Suggestion] 3DS cartage overwrite

### ISSUE THREAD

**Issue by MrDarius125** [d0k3/Decrypt9WIP#88]
you could add a feature so you could overwrite the cartage game and data so you could put a new game on a cartage like you could buy a really cheap game for the 3ds/NEW 3ds and overwrite it with a different game like cubic ninja so hax* could be easier and even get ds/dsi games to work too like fieldrunners so you could downgrade a 3ds from 11.0 to 9.2 or 2.1

**Comment by GrayJack** [comment]
It's called Read Only Memory (a.k.a. ROM) for a reason, we cannot write a thing in it (at least by software).
I saw some people do cartridge **hardware** mods in SNES to put a new game ROM in it, but I'm sure that it cannot be done by software only as you suggest.

**Comment by mariogamer2** [comment]
@GrayJack If it is a ROM only,yes,you cannot write it. But if it is a Flash ROM,that change all...

But me too I think it is ROM...

**Comment by Margen67** [comment]
![794](https://cloud.githubusercontent.com/assets/3462541/18412727/f8b126c6-774a-11e6-9be6-d33e3020cae8.png)

**Comment by dankzegriefer** [comment]
It's a ROM, you 'tard.

**Comment by hedgeberg** [comment]
There are 2 memories on any cartridge, CTR or NTR. The ROM, which stores your game, and is not rewritable, and the eepROM which holds your save files, which is rewritable but only holds saves. You can already edit saves using SVDT so theres no need for this in d9. Please don't request features before thoroughly reviewing these things.

**Comment by chaoskagami** [comment]
When these carts are written in the factory, they're written once, and only once.

If you managed to get your hands on a rewritable developer cart, that's a different story, but considering you're talking about rewriting a retail cart, I'm fairly sure you have no clue what you're asking.

**Comment by MrDarius125** [comment]
some roms can be overwriten

**Comment by dankzegriefer** [comment]
@MrDarius125 No.

**Comment by chaoskagami** [comment]
@MrDarius125, ROMs are read-only by definition. ROM = Read Only Memory.

**Comment by MrDarius125** [comment]
ok

**Comment by hedgeberg** [comment]
@MrDarius125 what are you talking about? do you mean eepROMs (electronically erasable programmable ROMs)? Because if that is what youre talking about, it doesnt apply to this situation since, again, the game is not stored in a reprogrammable ROM.

**Comment by MrDarius125** [comment]
then how is the save file done?

**Comment by kitling** [comment]
@MrDarius125 The save file is stored in a different part of the cartridge that is re-writable.

**Comment by dankzegriefer** [comment]
@MrDarius125 hedgeberg already explained

**Comment by hedgeberg** [comment]
The save file is stored on a physically separate chip that is an eeprom and is programmable.

**Comment by chaoskagami** [comment]
Hell, it's not even on the same chip

**Comment by Margen67** [comment]
![794](https://cloud.githubusercontent.com/assets/3462541/18412838/af98e8fe-774d-11e6-8960-38da15293c5d.png)

**Comment by mariogamer2** [comment]
So now,click on "Close issue" :P.

**Comment by d0k3** [comment]
As has been discussed enough - you can't overwrite retail cartridges. Just think about it, would we even need hardware like the Sky3DS if we could just buy "My Pony 3D" for $5 and rewrite it? No? Well, then this is closed now.
