### ISSUE TITLE
Allow Title Installation

### ISSUE THREAD

**Issue by gudenau** [d0k3/Decrypt9WIP#89]
It would be a nice feature to be able to allow the installation of NAND titles from D9, incase you broke a system title. NAND backups work, but this could be faster.

**Comment by mariogamer2** [comment]
Would be nice,yeah...

Just like this,it will be on what format?

**Comment by gudenau** [comment]
I would assume CIA.

**Comment by mariogamer2** [comment]
CIA does not need (to install) AM services (on ARM11)? (I'm a noob,this can be false...)

**Comment by gudenau** [comment]
What do you mean?

**Comment by mariogamer2** [comment]
You need to use AM services (and some other) to delete/install CIA,and I'm not sure if an ARM9 project can use ARM11 function (it's depend of the project...).

**Comment by gudenau** [comment]
You can't, but you could do what the ARM11/ARM9 services do to install a NAND title. There is an ARM9 payload that can do this.

**Comment by d0k3** [comment]
Link, @gudenau?

**Comment by gudenau** [comment]
It's WaitWay.

**Comment by ihaveamac** [comment]
what do you mean by GW? do you mean how it downgrades the NAND?

**Comment by gudenau** [comment]
Yeah, doesn't it install NAND titles?

**Comment by ihaveamac** [comment]
I heard it just replaces .app and .tmd files. so not an actual install. correct me if I'm wrong......

**Comment by gudenau** [comment]
That's basically an install, far as I know. This would more be for "installed a bad home menu without a backup" type of tool. NAND only.

**Comment by d0k3** [comment]
Wrong. That is an inject, not an install, and even an inject is not a trivial thing to do. An actual install involves correctly changing title.db and (maybe) ticket.db- we can't do that, though.

**Comment by gudenau** [comment]
Let it be injecting then, same purpose in this case.

**Comment by mariogamer2** [comment]
It will be good to replace a broken title,yeah...

**Comment by d0k3** [comment]
As I said, injection is not exactly trivial. We do it for H&S, but even there a lot of stuff has to be taken account for. If I'd really enable it for everything, I'd open a can of worms that I'd rather not. This idea is not of the table yet, but it is still rather unlikely.

**Comment by kasai07** [comment]
Hello

Only title.db file in the SD contains games and app

But!!!
Despite the first layer ctrnand
Some party are still encrypted

The title.db in nand contains maj and other app of 3ds itself

**Comment by d0k3** [comment]
Okay, going back to the start of this:
"It would be a nice feature to be able to allow the installation of NAND titles from D9, incase you broke a system title. NAND backups work, but this could be faster."

I think this is a very specific fuckup. For completely borked CTRNANDs, we now have CTRNAND transfer, and repairing just one system title can be done in GodeMode9 (just replace the TMD and APP files). Also, D9s source code does not exactly lend itself to this. So, closing this now.
