### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by MIKESDAMONEE** [d0k3/Decrypt9WIP#90]
I put my decrypt9 files where they should be, i use menuhax and on the bottom screen is red, on the top screen is text, this pops up for a few seconds before another red screen, then back to the homebrew menu.

**Comment by ihaveamac** [comment]
using a9lh? if not, system version?

**Comment by MIKESDAMONEE** [comment]
11.0 ( via totorial), and i don't know how to get a9lh

**Comment by MIKESDAMONEE** [comment]
11.0 ( via totorial), and i don't know how to get a9lh

**Comment by MIKESDAMONEE** [comment]
11.0 ( via totorial), and i don't know how to get a9lh

**Comment by MIKESDAMONEE** [comment]
11.0 ( via totorial), and i don't know how to get a9lh

**Comment by MIKESDAMONEE** [comment]
11.0 ( via totorial), and i don't know how to get a9lh

**Comment by MIKESDAMONEE** [comment]
sorry.

**Comment by ihaveamac** [comment]
"via tutorial" what tutorial do you mean?

**Comment by MIKESDAMONEE** [comment]
hes flame something.

**Comment by ihaveamac** [comment]
tutorial for......?

**Comment by MIKESDAMONEE** [comment]
tutorial for fbi, he even said to use rxtools but i don't know even how to get that.

**Comment by ihaveamac** [comment]
if your sysnand is 9.2 or lower, you can run Decrypt9 from there.

**Comment by MIKESDAMONEE** [comment]
how do i do that.

**Comment by ihaveamac** [comment]
run it from homebrew launcher in sysnand if it's 9.2, or use the browser or something if below 9.0

also see the readme: https://github.com/d0k3/Decrypt9WIP#how-to-run-this--entry-points

**Comment by kitling** [comment]
You said that you were on 11.0. Is this on an EmuNAND? Or on your SysNAND?

**Comment by MIKESDAMONEE** [comment]
what on earth is a sysnand or a emunand, im so confused right now. >:

**Comment by kitling** [comment]
... I think that it's safe to say that if you don't know, you can't do what you're trying to do.

SysNAND: Your normal system. Before a9lh, we try and keep that at 9.2 so that we can run, say, Decrypt9 or FBI and custom firmware. rxTools is a very old custom firmware for the 3ds that you shouldn't use anymore.

EmuNAND: An emulated system on your SD card that we can install any version firmware onto and not lose access to these things, when used with Custom Firmware, can do rather nice things.

**Comment by kitling** [comment]
By the very mention of rxTools, I think you were following a... *really* old guide, which has not been updated in, well, forever.

And it's sounding like you have an 11.0 sysNAND, which means it is probably not possible for you to do the things you are trying to do without spending money on getting your system down to the right version.

**Comment by kitling** [comment]
If you want more technical details on how to do such a thing, there are updated guides available to follow that we can link here. I would not reccomend using that tutorial you were using any more.

**Comment by MIKESDAMONEE** [comment]
do i have to spend money

**Comment by ihaveamac** [comment]
depends on what your sysnand version is. you haven't made that clear.

**Comment by MIKESDAMONEE** [comment]
11.0.33

**Comment by ihaveamac** [comment]
you can't use Decrypt9 then. your sysnand needs to be 9.2 or lower, or have arm9loaderhax installed.

**Comment by kitling** [comment]
(Also, to fix it, you need to spend money. Sorry.)

**Comment by MIKESDAMONEE** [comment]
thats the thing, how do i do ether of those.

**Comment by kitling** [comment]
If you do want to try and fix it, and install a9lh, you can follow this guide: https://github.com/Plailect/Guide/wiki

**Comment by MIKESDAMONEE** [comment]
thank you i will try this

**Comment by kitling** [comment]
Could you hit the button at the bottom of the page that says "Close Issue"?

**Comment by MIKESDAMONEE** [comment]
were is the download link to a9lh

**Comment by MIKESDAMONEE** [comment]
Someone please give me a tutorial.

**Comment by ihaveamac** [comment]
https://github.com/Plailect/Guide/wiki

use this guide to downgrade. on 11.0.0-33 you need either a hardmod or DSiware + other system with custom firmware. there's currently no other way.
