### ISSUE TITLE
Is there a way to go back to previous font or edit it somehow?

### ISSUE THREAD

**Issue by doctahoo** [d0k3/Decrypt9WIP#93]
Hi, I have a 2ds console and I switched to your latest Decrypt9WIP version recently. However, the font looks very small now on my 2ds console and it is not comfortable to use. Is there a way to get the old bigger font back or choose between both? It looks much better and is easier to read in smaller screens (2ds and old 3ds). Thanks for your help.

**Comment by d0k3** [comment]
Opened an issue for something that is in the readme... :/ compile with make FONT=ORIG or let someone else compile for you.

**Comment by doctahoo** [comment]
I see. Well, I'm not a coder myself, y'know. However I searched in Google and installed the latest devkitProUpdater in Windows and then compiled Decrypt9WIP with the command you said. Fortunately, it worked! (I know, it may seem pretty straightforward, but you must understand that I'm not used to compiling code so some directions are welcome). My suggestion is that a little general tutorial about how to install the needed files and compile this and other tools (in the readme, for instance) would come very handy. Also, maybe a better solution still would be just to include the option to switch fonts directly from the tool, if that were possible. That would be a nice improvement. Thank you again.

**Comment by fox8091** [comment]
Or..learn how this stuff works or deal with it. This isn't a forum. Anyone who legitimately needs to compile knows how.

**Comment by d0k3** [comment]
Yeah, this is right. Tbh, I'd prefer font switching myself, but if you understood the code you'd know why it doesn't work. Generic compile instructions have no place in the readme, so, no, won't ever be in there. 

I don't have anything against people compiling with different fonts and providing these builds to others, though.
