### ISSUE TITLE
error: invalid preprocessing directive #elifdef

### ISSUE THREAD

**Issue by accolon** [d0k3/Decrypt9WIP#97]
The recently added _#elifdef FONT_GB_ in draw.h causes the compilation to fail on my Mac. I don't know which preprocessors support this, but it seems to be a common problem.

Changing it to _#elif defined FONT_GB_ should resolve the problem, at least it did for me.

**Comment by gnmmarechal** [comment]
can confirm, I am unable to compile out of the box.

**Comment by d0k3** [comment]
Fixed in https://github.com/d0k3/Decrypt9WIP/commit/952fa3a2e1050b5cada23ce8dcc6529506bb9fae

**Comment by gnmmarechal** [comment]
I suppose this can now be closed?
