### ISSUE TITLE
Dumper Enhancement Suggestion

### ISSUE THREAD

**Issue by mos6507** [d0k3/Decrypt9WIP#98]
It would be helpful for those wanting clean dumps if the dumper could display whether the cart is card1 or card2 and if card2 give the option to blank the save area by filling with FF and for info's sake display the address of the save area

**Comment by d0k3** [comment]
Not a bad idea, but I still think that's more the stuff external tools should do. Cart dumps are per se identifying and unique because of the private header, and for changing / blanking this you would use an external tool.

I'll think about it, maybe there are more opinions, too?

**Comment by mos6507** [comment]
I was under the impression that the .3ds only contained unique data if it was a card2 with save data. Otherwise wouldnt crc32, md5, and sha1 differ from other dumps of the same game (specifically the no-intro.org dat)? I thought the private header was separate from the .3ds? I dont know much about private headers, I dont have a flash cart, and I struggled to find any info about where its contained in the cart

**Comment by d0k3** [comment]
You're actually right - private headers are handled differently per flashcart (stored in different places), thus they are not included in cart dumps.

**Comment by d0k3** [comment]
Working starting with commit https://github.com/d0k3/Decrypt9WIP/commit/dedcf6c2b562c039298307e46265ab4e08af5f06

Please also test!

**Comment by mos6507** [comment]
Thanks for adding this functionality. Appears to be working for what I was able to test. I do wonder though if detecting card2 by chekcingfor != 0xFFFFFFFF at 0x200 is the best way. If this address is ignored by card1 carts, any address could be put here in the future as an anti-piracy measure. A more foolproof way to detect card2 would be checking offset 0x18D which is 02 for card2.

The dumping output from D9 makes it seem like the dump is being carried out in the old way then the save area overwritten with 0xFF. If this is the case (my C isnt up to following the source well enough to tell) then the save area is being written twice (once direct from cart and once with 0xFF's). It would be faster to only dump to the save address then pad with 0xFF to the correct dump size.

I wonder if it would give the same result to just dump as a trimmed dump then pad to full dump size with 0xFF? I dont know how the end address is determined for trimming, but I would assume it will always be lower than the card2 save address

**Comment by d0k3** [comment]
Oh well, where to start...

Detecting this via the 0xFFFFFFFF is actually accurate, see here:
https://www.3dbrew.org/wiki/NCSD#Card_Info_Header

I'll add the second check in, though, seems to be accurate as well:
https://www.3dbrew.org/wiki/NCSD#Partition_Flags

Yup, the CARD2 save area is actually written twice, but the code is more clean, and it is easier that way. The additional time requirement for this is very small, and there are also only a handful of CARD2 games anyways.

And, well. You are correct, the padding is always just 0xFF. Up until the point where it is not. Meaning: Hiding data in the padding area is very much possible (although I can't name a single case). And, to my understanding, that is also the reason why we offer full dumps and not just trimmed ones.

Also, the CARD2 save area is always inside the padding. This is a writeable area, while the remainder of the cart memory is read only.
