### ISSUE TITLE
Suggestion: Decrypt9 Updater

### ISSUE THREAD

**Issue by MKWPlayer1337** [d0k3/Decrypt9WIP#99]
Just an idea for those who don't feel like checking the releases page every so often this app gets updated. Kinda like for Luma3DS, the updater checks from a specific URL containing the newer version and then installs by user acceptance. And also for both A9LH & Menuhax users. Please let me know if this is possible. Thank you. I only know basic Java and C# coding, so I cannot code this well to make it by myself, even if I were to learn how 3ds homebrews and apps are coded.

**Comment by fox8091** [comment]
..This is an issue section, not a forum. Go ask on GBATemp or something. This isn't an issue with Decrypt9.

**Comment by MKWPlayer1337** [comment]
Well jeez.. Sorry. Plus the issue before mine was a suggestion. So tell him the same thing as you did to me. Plus I would doubt on the GBATemp forum no one would pay any attention to me since there are so many users on that forum already.

**Comment by d0k3** [comment]
Try this one here:
https://github.com/LiquidFenrir/MultiUpdater

If it does not work for you, you may shoot @LiquidFenrir a bug report.
Closing this now...
